/// GMLive.js (c) YellowAfterlife, 2016-
(function(){function nb(a,b,c){if(b){var d=function(){};d.prototype=b.prototype;b=new d;for(var f in c)b[f]=c[f];c.toString!==Object.prototype.toString&&(b.toString=c.toString)}else b=c;a.prototype=b}function l(){return Z(this,"")}function ob(a){this.errorText=null;this.macroNodes=[];this.macroNames=[];this.enums=[];this.scripts=[];this.offset=0;this.source=a;this.tokens=pb(a);null!=this.tokens?(this.length=this.tokens.length,this.buildLoop(a.main)):(this.errorText=qb,this.errorPos=rb)}function W(a,
b){qb=b.toString()+": "+a;rb=b;return null}function pb(a,b){null==b&&(b=-1);var c,d,f,v,z,m,g,e=[];0<=b?(v=aa,z=ba,m=b):(v=1,m=z=0);var h=a.code,k=a.length;e.__parser__=this;for(var l=!1,p=0;m<k;){g=h.charCodeAt(m++);switch(g){case 9:case 13:case 32:continue;case 10:l&&(d=e.length-1,z=e[d],0==z[1]&&0==z[4]&&(e[d]=sb(z[2],z[3],!0)));++v;z=m;continue}var q=m-1,n=new S(a,v,m-z);switch(g){case 59:e.push(Tc(n));break;case 44:e.push(Uc(n));break;case 46:g=h.charCodeAt(m);if(48<=g&&57>=g){for(;++m,g=h.charCodeAt(m),
48<=g&&57>=g;);d=h.substring(q,m);e.push(N(n,parseFloat(d),d))}else e.push(tb(n));break;case 58:e.push(Vc(n));break;case 63:e.push(Wc(n));break;case 64:e.push(Xc(n));break;case 61:61==h.charCodeAt(m)?(++m,e.push(y(n,64))):e.push(F(n,-1));break;case 43:switch(h.charCodeAt(m)){case 61:++m;e.push(F(n,16));break;case 43:++m;e.push(ub(n,!0));break;default:e.push(y(n,16))}break;case 45:switch(h.charCodeAt(m)){case 61:++m;e.push(F(n,17));break;case 45:++m;e.push(ub(n,!1));break;default:e.push(y(n,17))}break;
case 47:switch(h.charCodeAt(m)){case 47:for(++m;m<k&&(d=h.charCodeAt(m),10!=d&&13!=d);)++m;break;case 42:for(++m;g=h.charCodeAt(m),10==g&&(++v,z=m),++m,m<k?(c=!0,42==g&&47==h.charCodeAt(m)&&(c=!1)):c=!1,c;);d=m;for(++m;++d<k;){switch(h.charCodeAt(d)){case 9:case 32:continue}break}break;case 61:++m;e.push(F(n,1));break;default:d=1,61==h.charCodeAt(m)?(++m,e.push(F(n,d))):e.push(y(n,d))}break;case 42:d=0;61==h.charCodeAt(m)?(++m,e.push(F(n,d))):e.push(y(n,d));break;case 37:d=2;61==h.charCodeAt(m)?(++m,
e.push(F(n,d))):e.push(y(n,d));break;case 38:38==h.charCodeAt(m)?(++m,d=80):d=49;61==h.charCodeAt(m)?(++m,e.push(F(n,d))):e.push(y(n,d));break;case 124:124==h.charCodeAt(m)?(++m,d=96):d=48;61==h.charCodeAt(m)?(++m,e.push(F(n,d))):e.push(y(n,d));break;case 94:94==h.charCodeAt(m)?(++m,d=65):d=50;61==h.charCodeAt(m)?(++m,e.push(F(n,d))):e.push(y(n,d));break;case 62:switch(h.charCodeAt(m)){case 61:++m;e.push(y(n,69));break;case 62:++m;d=33;61==h.charCodeAt(m)?(++m,e.push(F(n,d))):e.push(y(n,d));break;
default:e.push(y(n,68))}break;case 60:switch(h.charCodeAt(m)){case 61:++m;e.push(y(n,67));break;case 60:++m;d=32;61==h.charCodeAt(m)?(++m,e.push(F(n,d))):e.push(y(n,d));break;case 62:++m;d=65;61==h.charCodeAt(m)?(++m,e.push(F(n,d))):e.push(y(n,d));break;default:e.push(y(n,66))}break;case 33:61==h.charCodeAt(m)?(++m,d=65,61==h.charCodeAt(m)?(++m,e.push(F(n,d))):e.push(y(n,d))):e.push(ra(n,1));break;case 126:e.push(ra(n,2));break;case 40:e.push(sa(n));break;case 41:e.push(ta(n));break;case 91:e.push(Yc(n));
break;case 93:e.push(Zc(n));break;case 123:++p;e.push(vb(n));break;case 125:--p;if(0<=b&&0>p)return 0<=b&&(ua=m,aa=v,ba=z),e;e.push(wb(n));break;case 34:f=m;for(d=h.charCodeAt(m);d!=g&&m<k;d=h.charCodeAt(m))10==d&&(++v,z=m),++m;m<k?d=h.substring(f,m++):(W("Unclosed string",n),d=null);if(null==d)return null;e.push(ha(n,h.substring(q+1,m-1)));break;case 39:f=m;for(d=h.charCodeAt(m);d!=g&&m<k;d=h.charCodeAt(m))10==d&&(++v,z=m),++m;m<k?d=h.substring(f,m++):(W("Unclosed string",n),d=null);if(null==d)return null;
e.push(ha(n,h.substring(q+1,m-1)));break;case 96:q=m;g=h.charCodeAt(m);e.push(sa(n));for(c=!1;96!=g&&m<k;g=h.charCodeAt(m))if(++m,10==g)++v,z=m;else if(36==g&&(g=h.charCodeAt(m),123==g)){++m;n=new S(a,v,m-z);c?e.push(y(n,18)):c=!0;e.push(ha(n,h.substring(q,m-2)));aa=v;ba=z;g=pb(a,m);if(null==g)return null;v=aa;z=ba;q=m=ua;e.push(y(n,18));e.push(sa(n));n=new S(a,v,m-z);f=g.length;for(d=0;d<f;++d)e.push(g[d]);e.push(ta(n))}if(m>=k)return W("Unclosed string",n);++m;n=new S(a,v,m-z);c&&e.push(y(n,18));
e.push(ha(n,h.substring(q,m-1)));e.push(ta(n));break;case 35:for(q=m;m<k;)if(g=h.charCodeAt(m),95==g||97<=g&&122>=g||65<=g&&90>=g||48<=g&&57>=g)++m;else break;switch(h.substring(q,m)){case "define":for(;m<k;)if(g=h.charCodeAt(m),32==g||9==g)++m;else break;if((95==g||97<=g&&122>=g||65<=g&&90>=g)&&m<k){q=m;for(++m;m<k;)if(g=h.charCodeAt(m),95==g||97<=g&&122>=g||65<=g&&90>=g||48<=g&&57>=g)++m;else break;e.push(sb(n,h.substring(q,m),!1));l=!0}else return W("Expected a script name",n);break;case "macro":e.push($c(n));
break;case "endregion":case "region":for(;m<k&&(d=h.charCodeAt(m),10!=d&&13!=d);)++m;break;default:e.push(ad(n)),m=q}break;case 36:for(;m<k;)if(g=h.charCodeAt(m),48<=g&&57>=g||97<=g&&102>=g||65<=g&&70>=g)++m;else break;d="0x"+h.substring(q+1,m);e.push(N(n,va(d),d));break;default:if(97<=g&&122>=g||65<=g&&90>=g||95==g){for(;m<k;)if(g=h.charCodeAt(m),95==g||97<=g&&122>=g||65<=g&&90>=g||48<=g&&57>=g)++m;else break;d=h.substring(q,m);switch(d){case "global":e.push(w(n,0));break;case "true":e.push(N(n,
1,null));break;case "false":e.push(N(n,0,null));break;case "all":e.push(N(n,-3,null));break;case "noone":e.push(N(n,-4,null));break;case "undefined":e.push(xb(n));break;case "null":e.push(xb(n));break;case "begin":e.push(vb(n));break;case "end":e.push(wb(n));break;case "globalvar":e.push(w(n,1));break;case "var":e.push(w(n,2));break;case "enum":e.push(w(n,3));break;case "if":e.push(w(n,4));break;case "then":e.push(w(n,5));break;case "else":e.push(w(n,6));break;case "switch":e.push(w(n,7));break;case "case":e.push(w(n,
8));break;case "default":e.push(w(n,9));break;case "for":e.push(w(n,14));break;case "repeat":e.push(w(n,10));break;case "while":e.push(w(n,11));break;case "do":e.push(w(n,13));break;case "until":e.push(w(n,12));break;case "with":e.push(w(n,15));break;case "exit":e.push(w(n,19));break;case "return":e.push(w(n,18));break;case "break":e.push(w(n,17));break;case "continue":e.push(w(n,16));break;case "debugger":e.push(w(n,26));break;case "try":e.push(w(n,21));break;case "catch":e.push(w(n,22));break;case "throw":e.push(w(n,
23));break;case "div":e.push(y(n,3));break;case "mod":e.push(y(n,2));break;case "and":e.push(y(n,80));break;case "or":e.push(y(n,96));break;case "xor":e.push(y(n,65));break;case "not":e.push(ra(n,1));break;case "in":e.push(bd(n));break;case "argument":e.push(w(n,24));break;case "argument_count":e.push(w(n,25));break;default:if(c=8<=d.length)c=8,null==c?c=d.length:0>c&&(c=d.length+c),c=d.substr(0,c),c="argument"==c;c?(c=va(d.substring(8)),null!=c?e.push(cd(n,c)):e.push(yb(n,d))):e.push(yb(n,d))}}else if(48<=
g&&57>=g||46==g)if(120==h.charCodeAt(m)){for(++m;m<k;)if(g=h.charCodeAt(m),48<=g&&57>=g||97<=g&&102>=g||65<=g&&70>=g)++m;else break;d=h.substring(q,m);e.push(N(n,va(d),d))}else{--m;c=!1;for(d=null;m<k;)if(g=h.charCodeAt(m),46==g){if(c)return W("Extra dot in a number",n);++m;g=h.charCodeAt(m);if(95==g||97<=g&&122>=g||65<=g&&90>=g){d=h.substring(q,m-2);e.push(N(n,parseFloat(d),d));n=new S(a,v,m-z);e.push(tb(n));break}c=!0}else if(48<=g&&57>=g)++m;else break;if(null==d){for(;48==h.charCodeAt(q);)if(++q,
q>=m){--q;break}else if(46==h.charCodeAt(q)){--q;break}d=h.substring(q,m);e.push(N(n,parseFloat(d),d))}}else return W("Unexpected character `"+String.fromCodePoint(g)+"`",n)}}0<=b&&(ua=m,aa=v,ba=z);return e}function zb(a){a=a.split("\\").join("\\\\");a=a.split("\n").join("\\n");if(0>a.indexOf('"'))return'"'+a+'"';if(0>a.indexOf("'"))return"'"+a+"'";throw new ca("Can't print `"+a+"`");}function K(a,b,c,d){switch(b[1]){case 34:a.b+="global";break;case 9:a.b+=r(G);break;case 8:a.b+=r(A);break;default:a.b+=
"gml$inst(",k(a,b,c,2),a.b+=")"}}function t(a,b,c,d){wa(b)?k(a,b,c,2):(a.b+="0|",k(a,b,c,0))}function k(a,b,c,d){c.unshift(b);var f,v,e;switch(b[1]){case 101:a.b+="continue";break;case 15:a.b+="arguments.length";break;case 100:a.b+="break";break;case 99:a.b+="return 0";break;case 102:a.b+="debugger";break;case 0:a.b+="undefined";break;case 1:d=b[3];f=b[4];a.b=null!=f?a.b+(null==f?"null":""+f):a.b+(null==d?"null":""+d);break;case 2:a.b+=r(zb(b[3]));break;case 3:d=b[4];a.b+=r(d.value);a.b+="/* ";a.b+=
r(b[3].name);a.b+=".";a.b+=r(d.name);a.b+=" */";break;case 4:e=b[3];b=e.length;a.b+="[";if(0<b)for(k(a,e[0],c,2),d=1;d<b;++d)a.b+=", ",k(a,e[d],c,2);a.b+="]";break;case 5:f=b[3];e=b[4];b=e.length;a.b+="{";if(0<b)for(a.b+=" ",a.b+=r("js$"+f[0]),a.b+=": ",k(a,e[0],c,2),d=1;d<b;++d)a.b+=", ",a.b+=r("js$"+f[d]),a.b+=": ",k(a,e[d],c,2);a.b+=" ";a.b+=String.fromCodePoint(125);a.semicoAfter=a.b.length;break;case 8:a.b+="get$id(";a.b+=r(A);a.b+=")";break;case 9:a.b+="get$id(";a.b+=r(G);a.b+=")";break;case 84:d=
b[4];b=b[3];a.b+="var ";a.b+=null==b?"null":""+b;null!=d&&(a.b+=" = ",k(a,d,c,2));break;case 6:b=b[3];a.b+="if (!(";k(a,b,c,0);a.b+=" instanceof Array)) ";k(a,b,c,0);a.b+=" = []";break;case 17:a.b+=r("js$"+b[3]);a.b+="(";a.b+=r(A);a.b+=", ";a.b+=r(G);e=b[4];b=e.length;for(d=0;d<b;++d)a.b+=", ",k(a,e[d],c,2);a.b+=")";break;case 19:a.b+="gml$scripts[";k(a,b[3],c,0);a.b+="](";a.b+=r(A);a.b+=", ";a.b+=r(G);e=b[4];b=e.length;for(d=0;d<b;++d)a.b+=", ",k(a,e[d],c,2);a.b+=")";break;case 22:a.b+=r("gml$"+
b[4]);a.b+="(";K(a,b[3],c,d);e=b[5];b=e.length;for(d=0;d<b;++d)a.b+=", ",k(a,e[d],c,2);a.b+=")";break;case 18:a.b+=r("js$"+b[4]);a.b+="(";K(a,b[3],c,d);a.b+=", ";a.b+=r(A);e=b[5];b=e.length;for(d=0;d<b;++d)a.b+=", ",k(a,e[d],c,2);a.b+=")";break;case 20:e=b[3];f=b[4];X(e)?(a.b+="gml$scripts[",K(a,e,c,d),a.b+=".js$",a.b+=null==f?"null":""+f,a.b+="](",K(a,e,c,d),a.b+=", "):(a.b+="gml$fieldcall(",K(a,e,c,d),a.b+=", 'js$",a.b+=null==f?"null":""+f,a.b+="', ");a.b+=r(A);e=b[5];b=e.length;for(d=0;d<b;++d)a.b+=
", ",k(a,e[d],c,2);a.b+=")";break;case 21:f=b[3];a.b+=r("gml$"+f);a.b+="(";e=b[4];b=e.length;d=xa[f];null!=d?(a.b+=r(A),1<d&&(a.b+=", ",a.b+=r(G)),f=!0):f=!1;for(d=0;d<b;++d)f?a.b+=", ":f=!0,k(a,e[d],c,2);a.b+=")";break;case 11:b=b[3];a.b+=r(b.index);a.b+="/* ";a.b+=r(b.name);a.b+=" */";break;case 12:f=b[3];null!=ia?(b=ia[f],null==b?a.b+=null==f?"null":""+f:"string"==typeof b?a.b+=r(zb(b)):(a.b+=r(b),a.b+=" /* ",a.b+=null==f?"null":""+f,a.b+=" */")):a.b+=r("gml$"+f);break;case 28:0==(d&2)?(a.b+="(",
k(a,b[3],c,2),a.b+=" > 0.5)"):(k(a,b[3],c,2),a.b+=" > 0.5");break;case 29:0==(d&2)?(a.b+="(",k(a,b[3],c,2),a.b+=" ? 1 : 0)"):(k(a,b[3],c,2),a.b+=" ? 1 : 0");break;case 30:b[5]&&(a.b+="!");a.b+="gml$variable_instance_exists(";k(a,b[4],c,2);a.b+=", ";k(a,b[3],c,2);a.b+=")";break;case 26:f=b[3];0==(d&2)&&(a.b+="(");3!=f?(k(a,b[4],c,0),a.b+=" ",a.b+=r(P(f)),a.b+=" ",k(a,b[5],c,0)):(a.b+="div(",k(a,b[4],c,2),a.b+=", ",k(a,b[5],c,2),a.b+=")");0==(d&2)&&(a.b+=")");break;case 27:k(a,b[4],c,0);a.b+=" ";a.b+=
r(P(b[3]));a.b+="= ";k(a,b[5],c,0);break;case 25:switch(b[4]){case 2:f="~";break;case 1:f="!";break;case 0:f="-"}a.b+=null==f?"null":""+f;k(a,b[3],c,0);break;case 23:a.b+=b[4]?"++":"--";k(a,b[3],c,0);break;case 24:k(a,b[3],c,0);a.b+=b[4]?"++":"--";break;case 13:b=b[3];a.b+="argument";a.b+=null==b?"null":""+b;break;case 14:a.b+="arguments[";t(a,b[3],c,d);a.b+="]";break;case 31:b=b[3];a.b+=null==b?"null":""+b;break;case 32:d=b[3];a.b+=null==d?"null":""+d;a.b+=" = ";k(a,b[4],c,2);break;case 33:d=b[3];
a.b+=null==d?"null":""+d;a.b+=" ";a.b+=r(P(b[4]));a.b+="= ";k(a,b[5],c,2);break;case 34:a.b+="global.";a.b+=r("js$"+b[3]);break;case 35:a.b+="global.";a.b+=r("js$"+b[3]);a.b+=" = ";k(a,b[4],c,2);break;case 36:a.b+="global.";a.b+=r("js$"+b[3]);a.b+=" ";a.b+=r(P(b[4]));a.b+="= ";k(a,b[5],c,2);break;case 37:f=b[4];K(a,b[3],c,d);a.b+=".";a.b+="js$";a.b+=null==f?"null":""+f;break;case 38:f=b[4];K(a,b[3],c,d);a.b+=".";a.b+="js$";a.b+=null==f?"null":""+f;a.b+=" = ";k(a,b[5],c,2);break;case 39:f=b[4];K(a,
b[3],c,d);a.b+=".";a.b+="js$";a.b+=null==f?"null":""+f;a.b+=" ";a.b+=r(P(b[5]));a.b+="= ";k(a,b[6],c,2);break;case 40:f=b[3];a.b+="get$";a.b+=null==f?"null":""+f;a.b+="(";0!=(H[f]&4)&&(a.b+=r(A));a.b+=")";break;case 41:f=b[3];a.b+="set$";a.b+=null==f?"null":""+f;a.b+="(";0!=(H[f]&4)&&(a.b+=r(A),a.b+=", ");k(a,b[4],c,0);a.b+=")";break;case 42:d=b[3];a.b+="aop$";a.b+=null==d?"null":""+d;a.b+="(";0!=(H[d]&4)&&(a.b+=r(A),a.b+=", ");a.b+=r(T(b[4]));a.b+=", ";k(a,b[5],c,0);a.b+=")";break;case 43:f=b[4];
a.b+="get$";a.b+=null==f?"null":""+f;a.b+="(";K(a,b[3],c,d);a.b+=")";break;case 44:f=b[4];a.b+="set$";a.b+=null==f?"null":""+f;a.b+="(";K(a,b[3],c,d);a.b+=", ";k(a,b[5],c,0);a.b+=")";break;case 45:f=b[4];a.b+="aop$";a.b+=null==f?"null":""+f;a.b+="(";K(a,b[3],c,d);a.b+=", ";a.b+=r(T(b[5]));a.b+=", ";k(a,b[6],c,0);a.b+=")";break;case 46:d=b[3];a.b+="get$";a.b+=null==d?"null":""+d;a.b+="(";k(a,b[4],c,0);a.b+=")";break;case 47:d=b[3];a.b+="set$";a.b+=null==d?"null":""+d;a.b+="(";k(a,b[4],c,0);a.b+=", ";
k(a,b[5],c,0);a.b+=")";break;case 48:d=b[3];a.b+="set$";a.b+=null==d?"null":""+d;a.b+="(";k(a,b[4],c,0);a.b+=", ";k(a,b[6],c,0);a.b+=")";break;case 49:k(a,b[3],c,0);a.b+="[";t(a,b[4],c,d);a.b+="]";break;case 50:k(a,b[3],c,0);a.b+="[";t(a,b[4],c,d);a.b+="] = ";k(a,b[5],c,0);break;case 51:k(a,b[3],c,0);a.b+="[";t(a,b[4],c,d);a.b+="] ";a.b+=r(P(b[5]));a.b+="= ";k(a,b[6],c,0);break;case 52:a.b+=b[5]?"++":"--";k(a,b[3],c,0);a.b+="[";k(a,b[4],c,2);a.b+="]";break;case 53:k(a,b[3],c,0);a.b+="[";k(a,b[4],
c,2);a.b+="]";a.b+=b[5]?"++":"--";break;case 54:k(a,b[3],c,0);a.b+="[";t(a,b[4],c,d);a.b+="][";t(a,b[5],c,d);a.b+="]";break;case 55:a.b+="gml$";a.b+="array_set_2D";a.b+="(";k(a,b[3],c,0);a.b+=", ";t(a,b[4],c,d);a.b+=", ";t(a,b[5],c,d);a.b+=", ";k(a,b[6],c,0);a.b+=")";break;case 56:a.b+="gml$";a.b+="array_aop_2D";a.b+="(";k(a,b[3],c,0);a.b+=", ";t(a,b[4],c,d);a.b+=", ";t(a,b[5],c,d);a.b+=", ";a.b+=r(T(b[6]));a.b+=", ";k(a,b[7],c,0);a.b+=")";break;case 57:a.b+=b[6]?"++":"--";k(a,b[3],c,0);a.b+="[";
t(a,b[4],c,d);a.b+="][";t(a,b[5],c,d);a.b+="]";break;case 58:k(a,b[3],c,0);a.b+="[";t(a,b[4],c,d);a.b+="][";t(a,b[5],c,d);a.b+="]";a.b+=b[6]?"++":"--";break;case 59:k(a,b[3],c,0);a.b+="[";t(a,b[4],c,d);a.b+="]";break;case 60:k(a,b[3],c,0);a.b+="[";t(a,b[4],c,d);a.b+="] = ";k(a,b[5],c,2);break;case 61:k(a,b[3],c,0);a.b+="[";t(a,b[4],c,d);a.b+="] ";a.b+=r(P(b[5]));a.b+="= ";k(a,b[6],c,2);break;case 64:k(a,b[3],c,0);a.b+="[";t(a,b[4],c,d);a.b+="][";t(a,b[5],c,d);a.b+="]";break;case 65:a.b+="gml$";a.b+=
"array_set_2D";a.b+="(";k(a,b[3],c,0);a.b+=", ";t(a,b[4],c,d);a.b+=", ";t(a,b[5],c,d);a.b+=", ";k(a,b[6],c,0);a.b+=")";break;case 66:a.b+="gml$";a.b+="array_aop_2D";a.b+="(";k(a,b[3],c,0);a.b+=", ";t(a,b[4],c,d);a.b+=", ";t(a,b[5],c,d);a.b+=", ";a.b+=r(T(b[6]));a.b+=", ";k(a,b[7],c,0);a.b+=")";break;case 67:a.b+=b[6]?"++":"--";k(a,b[3],c,0);a.b+="[";t(a,b[4],c,d);a.b+="][";t(a,b[5],c,d);a.b+="]";break;case 68:k(a,b[3],c,0);a.b+="[";t(a,b[4],c,d);a.b+="][";t(a,b[5],c,d);a.b+="]";a.b+=b[6]?"++":"--";
break;case 69:a.b+="gml$";a.b+="ds_list_find_value";a.b+="(";k(a,b[3],c,0);a.b+=", ";k(a,b[4],c,0);a.b+=")";break;case 70:a.b+="gml$";a.b+="ds_list_set";a.b+="(";k(a,b[3],c,0);a.b+=", ";k(a,b[4],c,0);a.b+=", ";k(a,b[5],c,0);a.b+=")";break;case 71:a.b+="gml$";a.b+="ds_list_aop";a.b+="(";k(a,b[3],c,2);a.b+=", ";k(a,b[4],c,2);a.b+=", ";a.b+=r(T(b[5]));a.b+=", ";k(a,b[6],c,2);a.b+=")";break;case 72:a.b+="gml$";a.b+="ds_list_prefix";a.b+="(";k(a,b[3],c,2);a.b+=", ";k(a,b[4],c,2);a.b+=", ";a.b=b[5]?a.b+
"1":a.b+"-1";a.b+=")";break;case 73:a.b+="gml$";a.b+="ds_list_postfix";a.b+="(";k(a,b[3],c,2);a.b+=", ";k(a,b[4],c,2);a.b+=", ";a.b=b[5]?a.b+"1":a.b+"-1";a.b+=")";break;case 74:a.b+="gml$";a.b+="ds_map_find_value";a.b+="(";k(a,b[3],c,2);a.b+=", ";k(a,b[4],c,2);a.b+=")";break;case 75:a.b+="gml$";a.b+="ds_map_set";a.b+="(";k(a,b[3],c,2);a.b+=", ";k(a,b[4],c,2);a.b+=", ";k(a,b[5],c,2);a.b+=")";break;case 76:a.b+="gml$";a.b+="ds_map_aop";a.b+="(";k(a,b[3],c,2);a.b+=", ";k(a,b[4],c,2);a.b+=", ";a.b+=r(T(b[5]));
a.b+=", ";k(a,b[6],c,2);a.b+=")";break;case 77:a.b+="gml$";a.b+="ds_map_prefix";a.b+="(";k(a,b[3],c,2);a.b+=", ";k(a,b[4],c,2);a.b+=", ";a.b=b[5]?a.b+"1":a.b+"-1";a.b+=")";break;case 78:a.b+="gml$";a.b+="ds_map_postfix";a.b+="(";k(a,b[3],c,2);a.b+=", ";k(a,b[4],c,2);a.b+=", ";a.b=b[5]?a.b+"1":a.b+"-1";a.b+=")";break;case 79:a.b+="gml$";a.b+="ds_grid_get";a.b+="(";k(a,b[3],c,0);a.b+=", ";k(a,b[4],c,0);a.b+=", ";k(a,b[5],c,0);a.b+=")";break;case 80:a.b+="gml$";a.b+="ds_grid_set";a.b+="(";k(a,b[3],c,
0);a.b+=", ";k(a,b[4],c,0);a.b+=", ";k(a,b[5],c,0);a.b+=", ";k(a,b[6],c,0);a.b+=")";break;case 81:a.b+="gml$";a.b+="ds_grid_aop";a.b+="(";k(a,b[3],c,2);a.b+=", ";k(a,b[4],c,2);a.b+=", ";k(a,b[5],c,2);a.b+=", ";a.b+=r(T(b[6]));a.b+=", ";k(a,b[7],c,2);a.b+=")";break;case 82:a.b+="gml$";a.b+="ds_grid_prefix";a.b+="(";k(a,b[3],c,2);a.b+=", ";t(a,b[4],c,d);a.b+=", ";t(a,b[5],c,d);a.b+=", ";a.b=b[6]?a.b+"1":a.b+"-1";a.b+=")";break;case 83:a.b+="gml$";a.b+="ds_grid_postfix";a.b+="(";k(a,b[3],c,2);a.b+=", ";
t(a,b[4],c,d);a.b+=", ";t(a,b[5],c,d);a.b+=", ";a.b=b[6]?a.b+"1":a.b+"-1";a.b+=")";break;case 87:0==(d&2)&&(a.b+="(");k(a,b[3],c,0);a.b+=" ? ";k(a,b[4],c,0);a.b+=" : ";k(a,b[5],c,0);0==(d&2)&&(a.b+=")");break;case 86:d=b[5];null!=d?(a.b+="if (",k(a,b[3],c,2),a.b+=") {",a.indent+=1,a.addLine(),k(a,b[4],c,1),a.b.length>a.semicoAfter&&(a.b+=String.fromCodePoint(59),a.semicoAfter=a.b.length),--a.indent,a.addLine(),a.b+=String.fromCodePoint(125),a.semicoAfter=a.b.length,a.b+=" else ",k(a,d,c,0)):(a.b+=
"if (",k(a,b[3],c,2),a.b+=") ",k(a,b[4],c,0));break;case 88:e=b[5];v=b[4];a.b+="switch (";k(a,b[3],c,2);a.b+=") {";a.indent+=1;b=v.length;for(d=0;d<b;++d){var g=v[d].values;a.addLine();a.b+="case ";k(a,g[0],c,2);a.b+=":";for(f=1;f<g.length;++f)a.b+=" case ",k(a,g[f],c,2),a.b+=":";a.indent+=1;a.addLine();k(a,v[d].expr,c,1);a.b.length>a.semicoAfter&&(a.b+=String.fromCodePoint(59),a.semicoAfter=a.b.length);--a.indent}null!=e&&(a.addLine(),a.b+="default:",a.indent+=1,a.addLine(),k(a,e,c,1),a.b.length>
a.semicoAfter&&(a.b+=String.fromCodePoint(59),a.semicoAfter=a.b.length),--a.indent);--a.indent;a.addLine();a.b+=String.fromCodePoint(125);a.semicoAfter=a.b.length;break;case 85:e=b[3];b=e.length;if(1==b)k(a,e[0],c,d);else if(0==b)0==(d&1)&&(a.b+="{ ",a.b+=String.fromCodePoint(125),a.semicoAfter=a.b.length);else{if(v=0==(d&1))a.b+="{",a.indent+=1,a.addLine();f=!1;for(d=0;d<b;){f&&a.addLine();f=a.b.length;g=e[d];if(84==g[1]&&null==g[4])for(g=g[3],a.b+="var ",a.b+=null==g?"null":""+g;d+1<b;){g=e[d+1];
if(84==g[1]){var h=g[3];if(null==g[4]){a.b+=", ";a.b+=null==h?"null":""+h;++d;continue}}break}else k(a,e[d],c,5);(f=a.b.length>f)&&a.b.length>a.semicoAfter&&(a.b+=String.fromCodePoint(59),a.semicoAfter=a.b.length);107==e[d][1]&&(f=!1);++d}v&&(--a.indent,a.addLine(),a.b+=String.fromCodePoint(125),a.semicoAfter=a.b.length)}break;case 91:a.b+="while (";k(a,b[3],c,2);a.b+=") ";k(a,b[4],c,0);break;case 93:a.b+="do ";k(a,b[3],c,0);a.b.length>a.semicoAfter&&(a.b+=String.fromCodePoint(59),a.semicoAfter=a.b.length);
a.b+=" while (";k(a,b[4],c,2);a.b+=")";break;case 92:a.b+="do ";k(a,b[3],c,0);a.b.length>a.semicoAfter&&(a.b+=String.fromCodePoint(59),a.semicoAfter=a.b.length);a.b+=" while (";k(a,Ab(b[4]),c,2);a.b+=")";break;case 94:a.b+="repeat (";k(a,b[3],c,2);a.b+=") ";k(a,b[4],c,0);break;case 95:a.b+="for (";k(a,b[3],c,0);a.b.length>a.semicoAfter&&(a.b+=String.fromCodePoint(59),a.semicoAfter=a.b.length);a.b+=" ";k(a,b[4],c,2);a.b.length>a.semicoAfter&&(a.b+=String.fromCodePoint(59),a.semicoAfter=a.b.length);
a.b+=" ";k(a,b[5],c,0);a.b+=") ";k(a,b[6],c,0);break;case 96:e=b[3];v=b[4];switch(e[1]){case 8:k(a,v,c,d);break;case 9:f=A;A=G;G=f;k(a,v,c,d);f=A;A=G;G=f;break;default:0==(d&1)&&(a.b+="{",a.indent+=1,a.addLine());b=new ja;k(b,e,c,2);da++;f=G;G=A;A="gml$self"+da;e=new ja;k(e,v,c,1);v=a.b;g=ya;h=da;var l;for(l="";l.length<b.indent;)l+="\t";a.b=v+r(g(h,l,"\t",b.b,e.b));A=G;G=f;da--;0==(d&1)&&(--a.indent,a.addLine(),a.b+=String.fromCodePoint(125),a.semicoAfter=a.b.length)}break;case 97:a.b+="once(";k(a,
b[3],c,0);a.b+=")";break;case 98:a.b+="return ";k(a,b[3],c,2);break;case 105:b=b[3];a.b+="//";a.b+=null==b?"null":""+b;a.semicoAfter=a.b.length;break;case 106:f=b[3];a.b+="//";a.b+=null==f?"null":""+f;a.addLine();k(a,b[4],c,d);break;case 108:f=b[3];a.addLine();a.b+="//";a.b+=null==f?"null":""+f;a.addLine();k(a,b[4],c,d);break;case 107:e=b[4];f=0!=(d&4);k(a,b[3],c,d);f&&a.b.length>a.semicoAfter&&(a.b+=String.fromCodePoint(59),a.semicoAfter=a.b.length);a.b+=" //";a.b+=null==e?"null":""+e;a.addLine();
a.semicoAfter=a.b.length;f||a.addLine();break;case 109:b=b[3];a.b+="/*";a.b+=null==b?"null":""+b;a.b+="*/";a.semicoAfter=a.b.length;break;case 111:d=b[4];k(a,b[3],c,0);a.b+=" /*";a.b+=null==d?"null":""+d;a.b+="*/";break;case 110:d=b[3];a.b+="/*";a.b+=null==d?"null":""+d;a.b+="*/ ";k(a,b[4],c,0);break;case 103:d=b[4];a.b+="try {";a.indent+=1;a.addLine();a.semicoAfter=a.b.length;k(a,b[3],c,1);a.b.length>a.semicoAfter&&(a.b+=String.fromCodePoint(59),a.semicoAfter=a.b.length);--a.indent;a.addLine();a.b+=
String.fromCodePoint(125);a.semicoAfter=a.b.length;a.b+=" catch (";a.b+=null==d?"null":""+d;a.b+=") {";a.indent+=1;a.addLine();a.b+="if (";a.b+=null==d?"null":""+d;a.b+=" instanceof Error) ";a.b+=null==d?"null":""+d;a.b+=" = ";a.b+=null==d?"null":""+d;a.b+=".toString()";a.b.length>a.semicoAfter&&(a.b+=String.fromCodePoint(59),a.semicoAfter=a.b.length);a.addLine();a.semicoAfter=a.b.length;k(a,b[5],c,1);a.b.length>a.semicoAfter&&(a.b+=String.fromCodePoint(59),a.semicoAfter=a.b.length);--a.indent;a.addLine();
a.b+=String.fromCodePoint(125);a.semicoAfter=a.b.length;break;case 104:a.b+="throw ";k(a,b[3],c,2);break;default:a.b+='@ERROR"Unsupported structure: ',a.b+=r(b[0]),a.b+='"'}c.shift()}function dd(a){var b=new ja,c=a.scripts;for(a=0;a<c.length;++a){var d=b,f=c[a];A="self";G="other";da=0;var e=d,g=f;e.b+="function js$";e.b+=r(g.name);e.b+="(self, other";for(var h=0,g=g.arguments;h<g;h++)e.b+=", argument",e.b+=null==h?"null":""+h;e.b+=") ";e.indent+=1;e.b+="{";e.addLine();e=d;e.semicoAfter=e.b.length;
k(e,f.node,[],1);e.b.length>e.semicoAfter&&(e.b+=String.fromCodePoint(59),e.semicoAfter=e.b.length);--d.indent;d.addLine();d.b+=String.fromCodePoint(125);d.semicoAfter=d.b.length;b.addLine()}b.b+="var gml$scripts = [";for(a=0;a<c.length;++a)0<a&&(b.b+=", "),b.b+="js$",b.b+=r(c[a].name);b.b+="]";b.b.length>b.semicoAfter&&(b.b+=String.fromCodePoint(59),b.semicoAfter=b.b.length);b.addLine();return b.b}function Bb(a){this.isReady=!1;this.errorText=null;this.macros=Object.create(null);this.enumMap=Object.create(null);
this.enums=[];this.scriptMap=Object.create(null);this.scripts=[];this.sources=null;this.sources=a;for(var b=[],c=0;c<a.length;){var d=a[c];++c;var f=new ob(d);b.push(f);if(null==f.errorText){for(var d=d.main,e=0,g=f.scripts;e<g.length;){var h=g[e];++e;if(null!=this.scriptMap[h.name])if(h.name==d){var k=this.scriptMap[d].node;if(85==k[1]&&0==k[3].length){var k=this.scripts,l=k.indexOf(this.scriptMap[d]);-1!=l&&k.splice(l,1);this.scripts.push(h);this.scriptMap[h.name]=h}else{this.error('Cannot override prefix-script "'+
d+'" because it is not empty',h.pos);return}}else{this.error("Script "+h.name+" is already defined at "+this.scriptMap[h.name].pos.toString(),h.pos);return}else this.scripts.push(h),this.scriptMap[h.name]=h}d=0;for(e=f.enums;d<e.length;)g=e[d],++d,this.enums.push(g),this.enumMap[g.name]=g;d=f.macroNames;f=f.macroNodes;e=this.macros;g=0;for(h=d.length;g<h;g++)e[d[g]]=f[g]}else{this.errorText=f.errorText;this.errorPos=f.errorPos;return}}c=this.scripts.length;for(a=0;a<c;++a)this.scripts[a].index=a;
c=b.length;for(a=0;a<c&&!b[a].postcheck();++a);a>=c&&this.check()?u=null:this.isReady=!0}function Cb(){var a=L.contentWindow.setInterval(function(){var b=L.contentWindow;b.mark_avail&&(L.contentWindow.clearInterval(a),null!=M&&L.contentDocument.body.appendChild(M),za||(za=!0,ia=b.gml$constVal,ya=b.gml$withFunc,Aa=b.gml$asset_index,b=window.aceEditor,null!=b&&b.getSession().bgTokenizer.start(0)))},100)}function Y(a,b){null!=M&&(null!=M.parentElement&&M.parentElement.removeChild(M),M=null);var c=[],
d=0,f="",e=ea(window,"aceGetPairs");b&&(e=null);if(null!=e)for(var g=0,h=e(!0);g<h.length;){var k=h[g];++g;var l="game_tab_init_"+d++;c.push(new Db(k.name,k.code,l));f+=l+"();\n"}c.push(new Db("game_tab_init",f,"game_tab_init"));null!=e&&ea(window,"aceTabFlush")();c=new Bb(c);null!=e&&ea(window,"aceClearErrors")();if(null==c.errorText)if(null!=e&&ea(window,"aceHintText")("Compiled at "+(new Date).toLocaleTimeString()),M=document.createElement("script"),M.type="text/javascript",e=dd(c),e+="gml$game_start();\n",
M.innerHTML=e,window.console.log(e),a){L.onload=null;L.src="about:blank";L.onload=function(a){L.onload=null;Cb()};e=Eb.value;if(null==e||""==e)e="2d";L.src="./lw/"+e+"/index.html"}else Cb();else null!=e?(e=c.errorPos,ea(window,"aceHintError")(e.src.name,{row:e.row-1,column:e.col-1},c.errorText)):window.alert(c.errorText)}function Fb(a,b){var c=a.charCodeAt(b);return c!=c?void 0:c}function ea(a,b){try{return a[b]}catch(c){return null}}function q(a,b){var c=a.length,d=b.length;c>d&&a.splice(d,c-d);
for(c=0;c<d;c++)a[c]=b[c]}function r(a){return Z(a,"")}function va(a){var b=parseInt(a,10);if(0==b){var c=Fb(a,1);if(120==c||88==c)b=parseInt(a)}return isNaN(b)?null:b}function ed(a,b){this.ctrMap=Object.create(null);this.ctrList=[];this.name=a;this.pos=b}function fd(a,b,c){this.name=a;this.pos=b;this.node=c}function Gb(a){a=["Undefined",0,a];a.__enum__=p;a.toString=l;return a}function B(a,b,c){a=["Number",1,a,b,c];a.__enum__=p;a.toString=l;return a}function fa(a,b){var c=["CString",2,a,b];c.__enum__=
p;c.toString=l;return c}function Hb(a,b,c){a=["EnumCtr",3,a,b,c];a.__enum__=p;a.toString=l;return a}function Ba(a,b){var c=["ArrayDecl",4,a,b];c.__enum__=p;c.toString=l;return c}function Ib(a,b,c){a=["ObjectDecl",5,a,b,c];a.__enum__=p;a.toString=l;return a}function Ca(a,b){var c=["EnsureArray",6,a,b];c.__enum__=p;c.toString=l;return c}function Jb(a,b){var c=["Ident",7,a,b];c.__enum__=p;c.toString=l;return c}function Da(a){a=["Self",8,a];a.__enum__=p;a.toString=l;return a}function Ea(a){a=["Other",
9,a];a.__enum__=p;a.toString=l;return a}function Fa(a){a=["GlobalRef",10,a];a.__enum__=p;a.toString=l;return a}function Ga(a,b){var c=["Script",11,a,b];c.__enum__=p;c.toString=l;return c}function Kb(a,b){var c=["Const",12,a,b];c.__enum__=p;c.toString=l;return c}function Ha(a,b){var c=["ArgConst",13,a,b];c.__enum__=p;c.toString=l;return c}function Ia(a,b){var c=["ArgIndex",14,a,b];c.__enum__=p;c.toString=l;return c}function Ja(a){a=["ArgCount",15,a];a.__enum__=p;a.toString=l;return a}function Lb(a,
b,c){a=["Call",16,a,b,c];a.__enum__=p;a.toString=l;return a}function Mb(a,b,c){a=["CallScript",17,a,b,c];a.__enum__=p;a.toString=l;return a}function Nb(a,b,c,d){a=["CallScriptAt",18,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Ob(a,b,c,d){a=["CallField",20,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Pb(a,b,c){a=["CallFunc",21,a,b,c];a.__enum__=p;a.toString=l;return a}function Qb(a,b,c,d){a=["CallFuncAt",22,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Rb(a,b,c){a=["Prefix",
23,a,b,c];a.__enum__=p;a.toString=l;return a}function Sb(a,b,c){a=["Postfix",24,a,b,c];a.__enum__=p;a.toString=l;return a}function ka(a,b,c){a=["UnOp",25,a,b,c];a.__enum__=p;a.toString=l;return a}function D(a,b,c,d){a=["BinOp",26,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Ka(a,b,c,d){a=["SetOp",27,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Tb(a,b){var c=["FromBool",29,a,b];c.__enum__=p;c.toString=l;return c}function La(a,b,c,d){a=["In",30,a,b,c,d];a.__enum__=p;a.toString=l;return a}
function la(a,b){var c=["Local",31,a,b];c.__enum__=p;c.toString=l;return c}function Ub(a,b,c){a=["LocalSet",32,a,b,c];a.__enum__=p;a.toString=l;return a}function Vb(a,b,c,d){a=["LocalAop",33,a,b,c,d];a.__enum__=p;a.toString=l;return a}function ma(a,b){var c=["Global",34,a,b];c.__enum__=p;c.toString=l;return c}function Wb(a,b,c){a=["GlobalSet",35,a,b,c];a.__enum__=p;a.toString=l;return a}function Xb(a,b,c,d){a=["GlobalAop",36,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Ma(a,b,c){a=["Field",
37,a,b,c];a.__enum__=p;a.toString=l;return a}function Yb(a,b,c,d){a=["FieldSet",38,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Zb(a,b,c,d,f){a=["FieldAop",39,a,b,c,d,f];a.__enum__=p;a.toString=l;return a}function $b(a,b){var c=["Env",40,a,b];c.__enum__=p;c.toString=l;return c}function ac(a,b,c){a=["EnvSet",41,a,b,c];a.__enum__=p;a.toString=l;return a}function bc(a,b,c,d){a=["EnvAop",42,a,b,c,d];a.__enum__=p;a.toString=l;return a}function cc(a,b,c){a=["EnvFd",43,a,b,c];a.__enum__=p;a.toString=
l;return a}function dc(a,b,c,d){a=["EnvFdSet",44,a,b,c,d];a.__enum__=p;a.toString=l;return a}function ec(a,b,c,d,f){a=["EnvFdAop",45,a,b,c,d,f];a.__enum__=p;a.toString=l;return a}function Na(a,b,c){a=["Env1d",46,a,b,c];a.__enum__=p;a.toString=l;return a}function Oa(a,b,c,d){a=["Env1dSet",47,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Pa(a,b,c,d,f){a=["Env1dAop",48,a,b,c,d,f];a.__enum__=p;a.toString=l;return a}function fc(a,b,c){a=["Index",49,a,b,c];a.__enum__=p;a.toString=l;return a}function Qa(a,
b,c,d){a=["IndexSet",50,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Ra(a,b,c,d,f){a=["IndexAop",51,a,b,c,d,f];a.__enum__=p;a.toString=l;return a}function gc(a,b,c,d){a=["Index2d",54,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Sa(a,b,c,d,f){a=["Index2dSet",55,a,b,c,d,f];a.__enum__=p;a.toString=l;return a}function Ta(a,b,c,d,f,e){a=["Index2dAop",56,a,b,c,d,f,e];a.__enum__=p;a.toString=l;return a}function hc(a,b,c){a=["RawId",59,a,b,c];a.__enum__=p;a.toString=l;return a}function ic(a,
b,c,d){a=["RawIdSet",60,a,b,c,d];a.__enum__=p;a.toString=l;return a}function jc(a,b,c,d,f){a=["RawIdAop",61,a,b,c,d,f];a.__enum__=p;a.toString=l;return a}function kc(a,b,c,d){a=["RawId2d",64,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Ua(a,b,c,d,f){a=["RawId2dSet",65,a,b,c,d,f];a.__enum__=p;a.toString=l;return a}function Va(a,b,c,d,f,e){a=["RawId2dAop",66,a,b,c,d,f,e];a.__enum__=p;a.toString=l;return a}function lc(a,b,c){a=["DsList",69,a,b,c];a.__enum__=p;a.toString=l;return a}function sc(a,
b,c,d){a=["DsListSet",70,a,b,c,d];a.__enum__=p;a.toString=l;return a}function tc(a,b,c,d,f){a=["DsListAop",71,a,b,c,d,f];a.__enum__=p;a.toString=l;return a}function Wa(a,b,c,d){a=["DsListPrefix",72,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Xa(a,b,c,d){a=["DsListPostfix",73,a,b,c,d];a.__enum__=p;a.toString=l;return a}function uc(a,b,c){a=["DsMap",74,a,b,c];a.__enum__=p;a.toString=l;return a}function vc(a,b,c,d){a=["DsMapSet",75,a,b,c,d];a.__enum__=p;a.toString=l;return a}function wc(a,b,
c,d,f){a=["DsMapAop",76,a,b,c,d,f];a.__enum__=p;a.toString=l;return a}function Ya(a,b,c,d){a=["DsMapPrefix",77,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Za(a,b,c,d){a=["DsMapPostfix",78,a,b,c,d];a.__enum__=p;a.toString=l;return a}function xc(a,b,c,d){a=["DsGrid",79,a,b,c,d];a.__enum__=p;a.toString=l;return a}function yc(a,b,c,d,f){a=["DsGridSet",80,a,b,c,d,f];a.__enum__=p;a.toString=l;return a}function zc(a,b,c,d,f,e){a=["DsGridAop",81,a,b,c,d,f,e];a.__enum__=p;a.toString=l;return a}function $a(a,
b,c,d,f){a=["DsGridPrefix",82,a,b,c,d,f];a.__enum__=p;a.toString=l;return a}function ab(a,b,c,d,f){a=["DsGridPostfix",83,a,b,c,d,f];a.__enum__=p;a.toString=l;return a}function bb(a,b,c){a=["VarDecl",84,a,b,c];a.__enum__=p;a.toString=l;return a}function J(a,b){var c=["Block",85,a,b];c.__enum__=p;c.toString=l;return c}function Ac(a,b,c,d){a=["IfThen",86,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Bc(a,b,c,d){a=["Ternary",87,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Cc(a,b,c,d){a=
["Switch",88,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Dc(a,b){var c=["Wait",89,a,b];c.__enum__=p;c.toString=l;return c}function Ec(a,b,c){a=["While",91,a,b,c];a.__enum__=p;a.toString=l;return a}function cb(a,b,c){a=["DoWhile",93,a,b,c];a.__enum__=p;a.toString=l;return a}function Fc(a,b,c){a=["Repeat",94,a,b,c];a.__enum__=p;a.toString=l;return a}function db(a,b,c,d,f){a=["For",95,a,b,c,d,f];a.__enum__=p;a.toString=l;return a}function Gc(a,b,c){a=["With",96,a,b,c];a.__enum__=p;a.toString=
l;return a}function Hc(a,b){var c=["Return",98,a,b];c.__enum__=p;c.toString=l;return c}function na(a){a=["Exit",99,a];a.__enum__=p;a.toString=l;return a}function Ic(a){a=["Break",100,a];a.__enum__=p;a.toString=l;return a}function Jc(a){a=["Continue",101,a];a.__enum__=p;a.toString=l;return a}function Kc(a){a=["Debugger",102,a];a.__enum__=p;a.toString=l;return a}function Lc(a,b,c,d){a=["TryCatch",103,a,b,c,d];a.__enum__=p;a.toString=l;return a}function Mc(a,b){var c=["Throw",104,a,b];c.__enum__=p;c.toString=
l;return c}function U(a,b){var c=["CommentLine",105,a,b];c.__enum__=p;c.toString=l;return c}function eb(a,b,c){a=["CommentLinePre",106,a,b,c];a.__enum__=p;a.toString=l;return a}function fb(a,b,c){a=["CommentLinePost",107,a,b,c];a.__enum__=p;a.toString=l;return a}function gb(a,b,c){a=["CommentLineSep",108,a,b,c];a.__enum__=p;a.toString=l;return a}function oa(a,b){var c=["CommentBlock",109,a,b];c.__enum__=p;c.toString=l;return c}function pa(a,b,c,d){a=["CommentBlockPre",110,a,b,c,d];a.__enum__=p;a.toString=
l;return a}function Nc(a,b,c,d){a=["CommentBlockPost",111,a,b,c,d];a.__enum__=p;a.toString=l;return a}function X(a){var b,c;switch(a[1]){case 1:return!0;case 2:return!0;case 0:return!0;case 31:return!0;case 34:return!0;case 4:c=a[3];b=c.length;for(a=0;a<b;)if(X(c[a]))++a;else break;return a>=b;case 5:c=a[4];b=c.length;for(a=0;a<b;)if(X(c[a]))++a;else break;return a>=b;case 8:return!0;case 9:return!0;case 37:return X(a[3]);case 49:return X(a[3])&&X(a[4]);default:return!1}}function Oc(a){switch(a[1]){case 16:return!0;
case 27:return!0;case 84:return!0;case 23:return!0;case 24:return!0;default:return!1}}function Pc(a,b){if(null==b)return!1;switch(b[1]){case 85:return!0;case 86:return a!=b[3];case 91:return a!=b[3];case 93:return a!=b[4];case 92:return a!=b[4];case 94:return a!=b[3];case 95:return a!=b[4];case 88:return a!=b[3];default:return!1}}function Ab(a){switch(a[1]){case 1:switch(a[3]){case 1:return B(a[2],0,null);case 0:return B(a[2],1,null)}break;case 26:switch(a[3]){case 68:return D(a[2],67,a[4],a[5]);
case 69:return D(a[2],66,a[4],a[5]);case 66:return D(a[2],69,a[4],a[5]);case 67:return D(a[2],68,a[4],a[5]);case 64:return D(a[2],65,a[4],a[5]);case 65:return D(a[2],64,a[4],a[5])}}return ka(a[2],g(a),1)}function hb(a){switch(a[1]){case 25:return 1==a[4]&&!0;case 26:a:switch(a[3]){case 64:case 65:case 66:case 67:case 68:case 69:case 80:case 96:a=!0;break a;default:a=!1}return a;case 29:return!0;default:return!1}}function wa(a){switch(a[1]){case 21:switch(a[3]){case "ceil":case "floor":case "round":return!0;
default:return!1}case 1:return a=a[3],a==(a|0);case 29:return!0;case 26:switch(a[3]){case 1:return!1;case 3:return!0;case 0:case 2:case 16:case 17:return wa(a[4])&&wa(a[5]);case 32:case 33:case 48:case 49:case 50:return!0;case 64:case 65:case 66:case 67:case 68:case 69:case 80:case 96:return!0;default:return!1}default:return!1}}function Q(a,b){var c=a.length;if(b.length!=c)return!1;for(var d=0;d<c;)if(h(a[d],b[d]))++d;else return!1;return!0}function h(a,b){if(a[1]!=b[1])return!1;var c,d;switch(a[1]){case 8:return!0;
case 10:return!0;case 9:return!0;case 101:return!0;case 15:return!0;case 90:return!0;case 100:return!0;case 0:return!0;case 99:return!0;case 102:return!0;case 12:return 12==b[1]?a[3]==b[3]:!1;case 11:return 11==b[1]?a[3]==b[3]:!1;case 31:return 31==b[1]?a[3]==b[3]:!1;case 3:if(3==b[1]){var f=b[4];return a[3]==b[3]&&a[4]==f}return!1;case 2:return 2==b[1]?a[3]==b[3]:!1;case 25:if(25==b[1]){var e=b[4];return h(a[3],b[3])&&a[4]==e}return!1;case 22:if(22==b[1]){var g=b[5],m=b[4];return h(a[3],b[3])&&a[4]==
m&&Q(a[5],g)}return!1;case 7:return 7==b[1]?a[3]==b[3]:!1;case 67:if(67==b[1]){var k=b[6],l=b[5],p=b[4];return h(a[3],b[3])&&h(a[4],p)&&h(a[5],l)&&a[6]==k}return!1;case 23:if(23==b[1]){var q=b[4];return h(a[3],b[3])&&a[4]==q}return!1;case 24:if(24==b[1]){var r=b[4];return h(a[3],b[3])&&a[4]==r}return!1;case 76:if(76==b[1]){var t=b[6],u=b[5],n=b[4];return h(a[3],b[3])&&h(a[4],n)&&a[5]==u&&h(a[6],t)}return!1;case 26:if(26==b[1]){var w=b[5],x=b[4];return a[3]==b[3]&&h(a[4],x)&&h(a[5],w)}return!1;case 27:if(27==
b[1]){var y=b[5],A=b[4];return a[3]==b[3]&&h(a[4],A)&&h(a[5],y)}return!1;case 28:return 28==b[1]?h(a[3],b[3]):!1;case 29:return 29==b[1]?h(a[3],b[3]):!1;case 30:if(30==b[1]){var B=b[5],C=b[4];return h(a[3],b[3])&&h(a[4],C)&&a[5]==B}return!1;case 94:if(94==b[1]){var D=b[4];return h(a[3],b[3])&&h(a[4],D)}return!1;case 32:if(32==b[1]){var E=b[4];return a[3]==b[3]&&h(a[4],E)}return!1;case 33:if(33==b[1]){var F=b[5],G=b[4];return a[3]==b[3]&&a[4]==G&&h(a[5],F)}return!1;case 34:return 34==b[1]?a[3]==b[3]:
!1;case 35:if(35==b[1]){var H=b[4];return a[3]==b[3]&&h(a[4],H)}return!1;case 36:if(36==b[1]){var I=b[5],J=b[4];return a[3]==b[3]&&a[4]==J&&h(a[5],I)}return!1;case 37:if(37==b[1]){var K=b[4];return h(a[3],b[3])&&a[4]==K}return!1;case 38:if(38==b[1]){var L=b[5],M=b[4];return h(a[3],b[3])&&a[4]==M&&h(a[5],L)}return!1;case 39:if(39==b[1]){var N=b[6],O=b[5],P=b[4];return h(a[3],b[3])&&a[4]==P&&a[5]==O&&h(a[6],N)}return!1;case 21:if(21==b[1]){var R=b[4];return a[3]==b[3]&&Q(a[4],R)}return!1;case 20:if(20==
b[1]){var S=b[5],T=b[4];return h(a[3],b[3])&&a[4]==T&&Q(a[5],S)}return!1;case 19:if(19==b[1]){var U=b[4];return h(a[3],b[3])&&Q(a[4],U)}return!1;case 6:return 6==b[1]?h(a[3],b[3]):!1;case 18:if(18==b[1]){var V=b[5],W=b[4];return h(a[3],b[3])&&a[4]==W&&Q(a[5],V)}return!1;case 17:if(17==b[1]){var X=b[4];return a[3]==b[3]&&Q(a[4],X)}return!1;case 16:if(16==b[1]){var Y=b[4];return h(a[3],b[3])&&Q(a[4],Y)}return!1;case 1:if(1==b[1]){var Z=b[4];return a[3]==b[3]&&a[4]==Z}return!1;case 49:if(49==b[1]){var aa=
b[4];return h(a[3],b[3])&&h(a[4],aa)}return!1;case 50:if(50==b[1]){var ba=b[5],ca=b[4];return h(a[3],b[3])&&h(a[4],ca)&&h(a[5],ba)}return!1;case 51:if(51==b[1]){var da=b[6],ea=b[5],fa=b[4];return h(a[3],b[3])&&h(a[4],fa)&&a[5]==ea&&h(a[6],da)}return!1;case 52:if(52==b[1]){var ga=b[5],ha=b[4];return h(a[3],b[3])&&h(a[4],ha)&&a[5]==ga}return!1;case 53:if(53==b[1]){var ia=b[5],ja=b[4];return h(a[3],b[3])&&h(a[4],ja)&&a[5]==ia}return!1;case 54:if(54==b[1]){var ka=b[5],la=b[4];return h(a[3],b[3])&&h(a[4],
la)&&h(a[5],ka)}return!1;case 55:if(55==b[1]){var ma=b[6],na=b[5],oa=b[4];return h(a[3],b[3])&&h(a[4],oa)&&h(a[5],na)&&h(a[6],ma)}return!1;case 56:if(56==b[1]){var pa=b[7],qa=b[6],ra=b[5],sa=b[4];return h(a[3],b[3])&&h(a[4],sa)&&h(a[5],ra)&&a[6]==qa&&h(a[7],pa)}return!1;case 57:if(57==b[1]){var ta=b[6],ua=b[5],va=b[4];return h(a[3],b[3])&&h(a[4],va)&&h(a[5],ua)&&a[6]==ta}return!1;case 58:if(58==b[1]){var wa=b[6],xa=b[5],ya=b[4];return h(a[3],b[3])&&h(a[4],ya)&&h(a[5],xa)&&a[6]==wa}return!1;case 59:if(59==
b[1]){var za=b[4];return h(a[3],b[3])&&h(a[4],za)}return!1;case 60:if(60==b[1]){var Aa=b[5],Ba=b[4];return h(a[3],b[3])&&h(a[4],Ba)&&h(a[5],Aa)}return!1;case 61:if(61==b[1]){var Ca=b[6],Da=b[5],Fa=b[4];return h(a[3],b[3])&&h(a[4],Fa)&&a[5]==Da&&h(a[6],Ca)}return!1;case 62:if(62==b[1]){var Ha=b[5],Ia=b[4];return h(a[3],b[3])&&h(a[4],Ia)&&a[5]==Ha}return!1;case 63:if(63==b[1]){var Ja=b[5],Ka=b[4];return h(a[3],b[3])&&h(a[4],Ka)&&a[5]==Ja}return!1;case 64:if(64==b[1]){var La=b[5],Ma=b[4];return h(a[3],
b[3])&&h(a[4],Ma)&&h(a[5],La)}return!1;case 65:if(65==b[1]){var Na=b[6],Oa=b[5],Pa=b[4];return h(a[3],b[3])&&h(a[4],Pa)&&h(a[5],Oa)&&h(a[6],Na)}return!1;case 66:if(66==b[1]){var Qa=b[7],Ra=b[6],Sa=b[5],Ta=b[4];return h(a[3],b[3])&&h(a[4],Ta)&&h(a[5],Sa)&&a[6]==Ra&&h(a[7],Qa)}return!1;case 48:if(48==b[1]){var Wa=b[6],Xa=b[5],Ya=b[4];return a[3]==b[3]&&h(a[4],Ya)&&a[5]==Xa&&h(a[6],Wa)}return!1;case 68:if(68==b[1]){var Za=b[6],$a=b[5],ab=b[4];return h(a[3],b[3])&&h(a[4],ab)&&h(a[5],$a)&&a[6]==Za}return!1;
case 69:if(69==b[1]){var bb=b[4];return h(a[3],b[3])&&h(a[4],bb)}return!1;case 70:if(70==b[1]){var cb=b[5],db=b[4];return h(a[3],b[3])&&h(a[4],db)&&h(a[5],cb)}return!1;case 71:if(71==b[1]){var eb=b[6],fb=b[5],gb=b[4];return h(a[3],b[3])&&h(a[4],gb)&&a[5]==fb&&h(a[6],eb)}return!1;case 72:if(72==b[1]){var hb=b[5],ib=b[4];return h(a[3],b[3])&&h(a[4],ib)&&a[5]==hb}return!1;case 73:if(73==b[1]){var jb=b[5],kb=b[4];return h(a[3],b[3])&&h(a[4],kb)&&a[5]==jb}return!1;case 74:if(74==b[1]){var lb=b[4];return h(a[3],
b[3])&&h(a[4],lb)}return!1;case 75:if(75==b[1]){var mb=b[5],nb=b[4];return h(a[3],b[3])&&h(a[4],nb)&&h(a[5],mb)}return!1;case 47:if(47==b[1]){var ob=b[5],pb=b[4];return a[3]==b[3]&&h(a[4],pb)&&h(a[5],ob)}return!1;case 46:if(46==b[1]){var qb=b[4];return a[3]==b[3]&&h(a[4],qb)}return!1;case 77:if(77==b[1]){var rb=b[5],sb=b[4];return h(a[3],b[3])&&h(a[4],sb)&&a[5]==rb}return!1;case 78:if(78==b[1]){var tb=b[5],ub=b[4];return h(a[3],b[3])&&h(a[4],ub)&&a[5]==tb}return!1;case 79:if(79==b[1]){var vb=b[5],
wb=b[4];return h(a[3],b[3])&&h(a[4],wb)&&h(a[5],vb)}return!1;case 80:if(80==b[1]){var xb=b[6],yb=b[5],zb=b[4];return h(a[3],b[3])&&h(a[4],zb)&&h(a[5],yb)&&h(a[6],xb)}return!1;case 81:if(81==b[1]){var Ab=b[7],Bb=b[6],Cb=b[5],Db=b[4];return h(a[3],b[3])&&h(a[4],Db)&&h(a[5],Cb)&&a[6]==Bb&&h(a[7],Ab)}return!1;case 82:if(82==b[1]){var Eb=b[6],Fb=b[5],Gb=b[4];return h(a[3],b[3])&&h(a[4],Gb)&&h(a[5],Fb)&&a[6]==Eb}return!1;case 83:if(83==b[1]){var Hb=b[6],Ib=b[5],Jb=b[4];return h(a[3],b[3])&&h(a[4],Jb)&&
h(a[5],Ib)&&a[6]==Hb}return!1;case 84:var Ea=a[4];if(84==b[1]){var mc=b[4];return a[3]==b[3]?null!=Ea?null!=mc&&h(Ea,mc):null==mc:!1}return!1;case 85:return 85==b[1]?Q(a[3],b[3]):!1;case 86:var Ga=a[5];if(86==b[1]){var nc=b[5],Kb=b[4];return h(a[3],b[3])&&h(a[4],Kb)?null!=Ga?null!=nc&&h(Ga,nc):null==nc:!1}return!1;case 87:if(87==b[1]){var Lb=b[5],Mb=b[4];return h(a[3],b[3])&&h(a[4],Mb)&&h(a[5],Lb)}return!1;case 89:return 89==b[1]?h(a[3],b[3]):!1;case 45:if(45==b[1]){var Nb=b[6],Ob=b[5],Pb=b[4];return h(a[3],
b[3])&&a[4]==Pb&&a[5]==Ob&&h(a[6],Nb)}return!1;case 91:if(91==b[1]){var Qb=b[4];return h(a[3],b[3])&&h(a[4],Qb)}return!1;case 92:if(92==b[1]){var Rb=b[4];return h(a[3],b[3])&&h(a[4],Rb)}return!1;case 93:if(93==b[1]){var Sb=b[4];return h(a[3],b[3])&&h(a[4],Sb)}return!1;case 44:if(44==b[1]){var Tb=b[5],Ub=b[4];return h(a[3],b[3])&&a[4]==Ub&&h(a[5],Tb)}return!1;case 95:if(95==b[1]){var Vb=b[6],Wb=b[5],Xb=b[4];return h(a[3],b[3])&&h(a[4],Xb)&&h(a[5],Wb)&&h(a[6],Vb)}return!1;case 96:if(96==b[1]){var Yb=
b[4];return h(a[3],b[3])&&h(a[4],Yb)}return!1;case 97:return 97==b[1]?h(a[3],b[3]):!1;case 98:return 98==b[1]?h(a[3],b[3]):!1;case 43:if(43==b[1]){var Zb=b[4];return h(a[3],b[3])&&a[4]==Zb}return!1;case 14:return 14==b[1]?h(a[3],b[3]):!1;case 42:if(42==b[1]){var $b=b[5],ac=b[4];return a[3]==b[3]&&a[4]==ac&&h(a[5],$b)}return!1;case 41:if(41==b[1]){var bc=b[4];return a[3]==b[3]&&h(a[4],bc)}return!1;case 103:if(103==b[1]){var cc=b[5],dc=b[4];return h(a[3],b[3])&&a[4]==dc&&h(a[5],cc)}return!1;case 104:return 104==
b[1]?h(a[3],b[3]):!1;case 105:return 105==b[1]?a[3]==b[3]:!1;case 106:if(106==b[1]){var ec=b[4];return a[3]==b[3]&&h(a[4],ec)}return!1;case 107:if(107==b[1]){var fc=b[4];return h(a[3],b[3])&&a[4]==fc}return!1;case 108:if(108==b[1]){var gc=b[4];return a[3]==b[3]&&h(a[4],gc)}return!1;case 109:return 109==b[1]?a[3]==b[3]:!1;case 110:if(110==b[1]){var hc=b[5],ic=b[4];return a[3]==b[3]&&h(a[4],ic)&&a[5]==hc}return!1;case 111:if(111==b[1]){var jc=b[5],kc=b[4];return h(a[3],b[3])&&a[4]==kc&&a[5]==jc}return!1;
case 40:return 40==b[1]?a[3]==b[3]:!1;case 13:return 13==b[1]?a[3]==b[3]:!1;case 4:return 4==b[1]?Q(a[3],b[3]):!1;case 5:var Ua=a[4];if(5==b[1]){var Va=b[4],lc=b[3];d=Ua.length;if(Va.length==d){for(c=0;c<d;)if(a[3][c]==lc[c]&&h(Ua[c],Va[c]))++c;else break;return c>=d}}return!1;case 88:var oc=a[5],pc=a[4];if(88==b[1]){var qc=b[5],rc=b[4];if(h(a[3],b[3])&&(null!=oc&&null!=qc&&h(oc,qc)||null==oc&&null==qc)){d=pc.length;if(rc.length!=d)return!1;for(c=0;c<d;)if(h(pc[c].expr,rc[c].expr)&&Q(pc[c].values,
rc[c].values))++c;else break;return c>=d}}return!1}}function ib(a){return null!=a?g(a):null}function g(a){var b,c,d,f;c=a[2];switch(a[1]){case 0:return Gb(c);case 3:return Hb(c,a[3],a[4]);case 5:b=a[4].slice();for(f=b.length;0<=--f;)b[f]=g(b[f]);return Ib(c,a[3].slice(0),b);case 6:return Ca(c,g(a[3]));case 7:return Jb(c,a[3]);case 8:return Da(c);case 2:return fa(c,a[3]);case 10:return Fa(c);case 11:return Ga(c,a[3]);case 12:return Kb(c,a[3]);case 14:return Ia(c,g(a[3]));case 15:return Ja(c);case 16:b=
a[4].slice();for(f=b.length;0<=--f;)b[f]=g(b[f]);return Lb(c,g(a[3]),b);case 17:b=a[4].slice();for(f=b.length;0<=--f;)b[f]=g(b[f]);return Mb(c,a[3],b);case 18:b=a[5].slice();for(f=b.length;0<=--f;)b[f]=g(b[f]);return Nb(c,g(a[3]),a[4],b);case 19:b=a[4].slice();for(f=b.length;0<=--f;)b[f]=g(b[f]);a=g(a[3]);a=["CallScriptId",19,c,a,b];a.__enum__=p;a.toString=l;return a;case 20:b=a[5].slice();for(f=b.length;0<=--f;)b[f]=g(b[f]);return Ob(c,g(a[3]),a[4],b);case 21:b=a[4].slice();for(f=b.length;0<=--f;)b[f]=
g(b[f]);return Pb(c,a[3],b);case 22:b=a[5].slice();for(f=b.length;0<=--f;)b[f]=g(b[f]);return Qb(c,g(a[3]),a[4],b);case 23:return Rb(c,g(a[3]),a[4]);case 24:return Sb(c,g(a[3]),a[4]);case 25:return ka(c,g(a[3]),a[4]);case 26:return D(c,a[3],g(a[4]),g(a[5]));case 27:return Ka(c,a[3],g(a[4]),g(a[5]));case 28:return a=g(a[3]),a=["ToBool",28,c,a],a.__enum__=p,a.toString=l,a;case 9:return Ea(c);case 30:return La(c,g(a[3]),g(a[4]),a[5]);case 31:return la(c,a[3]);case 32:return Ub(c,a[3],g(a[4]));case 33:return Vb(c,
a[3],a[4],g(a[5]));case 34:return ma(c,a[3]);case 35:return Wb(c,a[3],g(a[4]));case 36:return Xb(c,a[3],a[4],g(a[5]));case 37:return Ma(c,g(a[3]),a[4]);case 38:return Yb(c,g(a[3]),a[4],g(a[5]));case 39:return Zb(c,g(a[3]),a[4],a[5],g(a[6]));case 41:return ac(c,a[3],g(a[4]));case 42:return bc(c,a[3],a[4],g(a[5]));case 43:return cc(c,g(a[3]),a[4]);case 44:return dc(c,g(a[3]),a[4],g(a[5]));case 45:return ec(c,g(a[3]),a[4],a[5],g(a[6]));case 46:return Na(c,a[3],g(a[4]));case 47:return Oa(c,a[3],g(a[4]),
g(a[5]));case 48:return Pa(c,a[3],g(a[4]),a[5],g(a[6]));case 49:return fc(c,g(a[3]),g(a[4]));case 50:return Qa(c,g(a[3]),g(a[4]),g(a[5]));case 51:return Ra(c,g(a[3]),g(a[4]),a[5],g(a[6]));case 52:return b=g(a[3]),f=g(a[4]),a=["IndexPrefix",52,c,b,f,a[5]],a.__enum__=p,a.toString=l,a;case 53:return b=g(a[3]),f=g(a[4]),a=["IndexPostfix",53,c,b,f,a[5]],a.__enum__=p,a.toString=l,a;case 54:return gc(c,g(a[3]),g(a[4]),g(a[5]));case 55:return Sa(c,g(a[3]),g(a[4]),g(a[5]),g(a[6]));case 56:return Ta(c,g(a[3]),
g(a[4]),g(a[5]),a[6],g(a[7]));case 57:return b=g(a[3]),f=g(a[4]),d=g(a[5]),a=["Index2dPrefix",57,c,b,f,d,a[6]],a.__enum__=p,a.toString=l,a;case 58:return b=g(a[3]),f=g(a[4]),d=g(a[5]),a=["Index2dPostfix",58,c,b,f,d,a[6]],a.__enum__=p,a.toString=l,a;case 59:return hc(c,g(a[3]),g(a[4]));case 60:return ic(c,g(a[3]),g(a[4]),g(a[5]));case 61:return jc(c,g(a[3]),g(a[4]),a[5],g(a[6]));case 62:return b=g(a[3]),f=g(a[4]),a=["RawIdPrefix",62,c,b,f,a[5]],a.__enum__=p,a.toString=l,a;case 63:return b=g(a[3]),
f=g(a[4]),a=["RawIdPostfix",63,c,b,f,a[5]],a.__enum__=p,a.toString=l,a;case 64:return kc(c,g(a[3]),g(a[4]),g(a[5]));case 65:return Ua(c,g(a[3]),g(a[4]),g(a[5]),g(a[6]));case 66:return Va(c,g(a[3]),g(a[4]),g(a[5]),a[6],g(a[7]));case 67:return b=g(a[3]),f=g(a[4]),d=g(a[5]),a=["RawId2dPrefix",67,c,b,f,d,a[6]],a.__enum__=p,a.toString=l,a;case 68:return b=g(a[3]),f=g(a[4]),d=g(a[5]),a=["RawId2dPostfix",68,c,b,f,d,a[6]],a.__enum__=p,a.toString=l,a;case 69:return lc(c,g(a[3]),g(a[4]));case 70:return sc(c,
g(a[3]),g(a[4]),g(a[5]));case 71:return tc(c,g(a[3]),g(a[4]),a[5],g(a[6]));case 72:return Wa(c,g(a[3]),g(a[4]),a[5]);case 73:return Xa(c,g(a[3]),g(a[4]),a[5]);case 74:return uc(c,g(a[3]),g(a[4]));case 75:return vc(c,g(a[3]),g(a[4]),g(a[5]));case 76:return wc(c,g(a[3]),g(a[4]),a[5],g(a[6]));case 77:return Ya(c,g(a[3]),g(a[4]),a[5]);case 78:return Za(c,g(a[3]),g(a[4]),a[5]);case 79:return xc(c,g(a[3]),g(a[4]),g(a[5]));case 80:return yc(c,g(a[3]),g(a[4]),g(a[5]),g(a[6]));case 81:return zc(c,g(a[3]),
g(a[4]),g(a[5]),a[6],g(a[7]));case 82:return $a(c,g(a[3]),g(a[4]),g(a[5]),a[6]);case 83:return ab(c,g(a[3]),g(a[4]),g(a[5]),a[6]);case 84:return bb(c,a[3],ib(a[4]));case 85:b=a[3].slice();for(f=b.length;0<=--f;)b[f]=g(b[f]);return J(c,b);case 86:return Ac(c,g(a[3]),g(a[4]),ib(a[5]));case 87:return Bc(c,g(a[3]),g(a[4]),g(a[5]));case 29:return Tb(c,g(a[3]));case 89:return Dc(c,g(a[3]));case 90:return a=["Fork",90,c],a.__enum__=p,a.toString=l,a;case 91:return Ec(c,g(a[3]),g(a[4]));case 92:return b=g(a[3]),
a=g(a[4]),a=["DoUntil",92,c,b,a],a.__enum__=p,a.toString=l,a;case 93:return cb(c,g(a[3]),g(a[4]));case 94:return Fc(c,g(a[3]),g(a[4]));case 95:return db(c,g(a[3]),g(a[4]),g(a[5]),g(a[6]));case 96:return Gc(c,g(a[3]),g(a[4]));case 97:return a=g(a[3]),a=["Once",97,c,a],a.__enum__=p,a.toString=l,a;case 98:return Hc(c,g(a[3]));case 99:return na(c);case 100:return Ic(c);case 101:return Jc(c);case 102:return Kc(c);case 103:return Lc(c,g(a[3]),a[4],g(a[5]));case 104:return Mc(c,g(a[3]));case 105:return U(c,
a[3]);case 106:return eb(c,a[3],g(a[4]));case 107:return fb(c,g(a[3]),a[4]);case 108:return gb(c,a[3],g(a[4]));case 109:return oa(c,a[3]);case 110:return pa(c,a[3],g(a[4]),a[5]);case 111:return Nc(c,g(a[3]),a[4],a[5]);case 40:return $b(c,a[3]);case 13:return Ha(c,a[3]);case 4:b=a[3].slice();for(f=b.length;0<=--f;)b[f]=g(b[f]);return Ba(c,b);case 1:return B(c,a[3],a[4]);case 88:var e=a[4],e=e.slice();d=e.length;for(c=0;c<d;++c){var h=e[c];b=h.values.slice();for(f=b.length;0<=--f;)b[f]=g(b[f]);h={values:b,
expr:g(h.expr),pre:h.pre};e[c]=h;b=h.pre.slice();for(f=b.length;0<=--f;)b[f]=g(b[f]);h.pre=b}return Cc(a[2],g(a[3]),e,ib(a[5]))}}function jb(a,b,c,d){var f,e,g=b[d];if(null==g)return!1;switch(g[1]){case 85:f=g[3];for(e=f.length;0<=--e&&f[e]!=a;);for(;0<=--e;)if(c(f[e],null))return!0;break;case 86:f=g[3];if(f!=a&&c(f,null))return!0;break;case 91:f=g[3];if(f!=a&&c(f,null))return!0;break;case 93:f=g[3];if(f!=a&&c(f,null))return!0;break;case 92:f=g[3];if(f!=a&&c(f,null))return!0;break;case 94:f=g[3];
if(f!=a&&c(f,null))return!0;break;case 95:f=g[3];if(f!=a&&c(f,null))return!0;break;case 88:f=g[3];if(f!=a&&c(f,null))return!0;break;case 96:f=g[3];if(f!=a&&c(f,null))return!0;break;case 107:break;case 106:break;case 108:break;case 110:break;case 111:break;default:throw new ca("Can't seekAllOut over "+g[2].toString()+" "+g[0]);}return jb(g,b,c,d+1)}function I(a,b,c){null!=b&&b.unshift(a);var d,f,e,g,h;switch(a[1]){case 0:d=!1;break;case 3:d=!1;break;case 5:a=a[4];e=a.length;for(f=0;f<e&&!c(a[f],b);++f);
d=f<e;break;case 6:d=c(a[3],b);break;case 7:d=!1;break;case 8:d=!1;break;case 2:d=!1;break;case 10:d=!1;break;case 11:d=!1;break;case 12:d=!1;break;case 14:d=c(a[3],b);break;case 15:d=!1;break;case 16:if(c(a[3],b))d=!0;else{a=a[4];e=a.length;for(f=0;f<e&&!c(a[f],b);++f);d=f<e}break;case 17:a=a[4];e=a.length;for(f=0;f<e&&!c(a[f],b);++f);d=f<e;break;case 18:if(c(a[3],b))d=!0;else{a=a[5];e=a.length;for(f=0;f<e&&!c(a[f],b);++f);d=f<e}break;case 19:if(c(a[3],b))d=!0;else{a=a[4];e=a.length;for(f=0;f<e&&
!c(a[f],b);++f);d=f<e}break;case 20:if(c(a[3],b))d=!0;else{a=a[5];e=a.length;for(f=0;f<e&&!c(a[f],b);++f);d=f<e}break;case 21:a=a[4];e=a.length;for(f=0;f<e&&!c(a[f],b);++f);d=f<e;break;case 22:if(c(a[3],b))d=!0;else{a=a[5];e=a.length;for(f=0;f<e&&!c(a[f],b);++f);d=f<e}break;case 23:d=c(a[3],b);break;case 24:d=c(a[3],b);break;case 25:d=c(a[3],b);break;case 26:d=c(a[4],b)||c(a[5],b);break;case 27:d=c(a[4],b)||c(a[5],b);break;case 28:d=c(a[3],b);break;case 9:d=!1;break;case 30:d=c(a[3],b)||c(a[4],b);
break;case 31:d=!1;break;case 32:d=c(a[4],b);break;case 33:d=c(a[5],b);break;case 34:d=!1;break;case 35:d=c(a[4],b);break;case 36:d=c(a[5],b);break;case 37:d=c(a[3],b);break;case 38:d=c(a[3],b)||c(a[5],b);break;case 39:d=c(a[3],b)||c(a[6],b);break;case 41:d=c(a[4],b);break;case 42:d=c(a[5],b);break;case 43:d=c(a[3],b);break;case 44:d=c(a[3],b)||c(a[5],b);break;case 45:d=c(a[3],b)||c(a[6],b);break;case 46:d=c(a[4],b);break;case 47:d=c(a[4],b)||c(a[5],b);break;case 48:d=c(a[4],b)||c(a[6],b);break;case 49:d=
c(a[3],b)||c(a[4],b);break;case 50:d=c(a[3],b)||c(a[4],b)||c(a[5],b);break;case 51:d=c(a[3],b)||c(a[4],b)||c(a[6],b);break;case 52:d=c(a[3],b)||c(a[4],b);break;case 53:d=c(a[3],b)||c(a[4],b);break;case 54:d=c(a[3],b)||c(a[4],b)||c(a[5],b);break;case 55:d=c(a[3],b)||c(a[4],b)||c(a[5],b)||c(a[6],b);break;case 56:d=c(a[3],b)||c(a[4],b)||c(a[5],b)||c(a[7],b);break;case 57:d=c(a[3],b)||c(a[4],b)||c(a[5],b);break;case 58:d=c(a[3],b)||c(a[4],b)||c(a[5],b);break;case 59:d=c(a[3],b)||c(a[4],b);break;case 60:d=
c(a[3],b)||c(a[4],b)||c(a[5],b);break;case 61:d=c(a[3],b)||c(a[4],b)||c(a[6],b);break;case 62:d=c(a[3],b)||c(a[4],b);break;case 63:d=c(a[3],b)||c(a[4],b);break;case 64:d=c(a[3],b)||c(a[4],b)||c(a[5],b);break;case 65:d=c(a[3],b)||c(a[4],b)||c(a[5],b)||c(a[6],b);break;case 66:d=c(a[3],b)||c(a[4],b)||c(a[5],b)||c(a[7],b);break;case 67:d=c(a[3],b)||c(a[4],b)||c(a[5],b);break;case 68:d=c(a[3],b)||c(a[4],b)||c(a[5],b);break;case 69:d=c(a[3],b)||c(a[4],b);break;case 70:d=c(a[3],b)||c(a[4],b)||c(a[5],b);
break;case 71:d=c(a[3],b)||c(a[4],b)||c(a[6],b);break;case 72:d=c(a[3],b)||c(a[4],b);break;case 73:d=c(a[3],b)||c(a[4],b);break;case 74:d=c(a[3],b)||c(a[4],b);break;case 75:d=c(a[3],b)||c(a[4],b)||c(a[5],b);break;case 76:d=c(a[3],b)||c(a[4],b)||c(a[6],b);break;case 77:d=c(a[3],b)||c(a[4],b);break;case 78:d=c(a[3],b)||c(a[4],b);break;case 79:d=c(a[3],b)||c(a[4],b)||c(a[5],b);break;case 80:d=c(a[3],b)||c(a[4],b)||c(a[5],b)||c(a[6],b);break;case 81:d=c(a[3],b)||c(a[4],b)||c(a[5],b)||c(a[7],b);break;
case 82:d=c(a[3],b)||c(a[4],b)||c(a[5],b);break;case 83:d=c(a[3],b)||c(a[4],b)||c(a[5],b);break;case 84:d=a[4];d=null!=d&&c(d,b);break;case 85:a=a[3];e=a.length;for(f=0;f<e&&!c(a[f],b);++f);d=f<e;break;case 86:d=a[5];d=c(a[3],b)||c(a[4],b)||null!=d&&c(d,b);break;case 87:d=c(a[3],b)||c(a[4],b)||c(a[5],b);break;case 29:d=c(a[3],b);break;case 89:d=c(a[3],b);break;case 90:d=!1;break;case 91:d=c(a[3],b)||c(a[4],b);break;case 92:d=c(a[3],b)||c(a[4],b);break;case 93:d=c(a[3],b)||c(a[4],b);break;case 94:d=
c(a[3],b)||c(a[4],b);break;case 95:d=c(a[3],b)||c(a[4],b)||c(a[5],b)||c(a[6],b);break;case 96:d=c(a[3],b)||c(a[4],b);break;case 97:d=c(a[3],b);break;case 98:d=c(a[3],b);break;case 99:d=!1;break;case 100:d=!1;break;case 101:d=!1;break;case 102:d=!1;break;case 103:d=c(a[3],b)||c(a[5],b);break;case 104:d=c(a[3],b);break;case 105:d=!1;break;case 106:d=c(a[4],b);break;case 107:d=c(a[3],b);break;case 108:d=c(a[4],b);break;case 109:d=!1;break;case 110:d=c(a[4],b);break;case 111:d=c(a[3],b);break;case 40:d=
!1;break;case 13:d=!1;break;case 4:a=a[3];e=a.length;for(f=0;f<e&&!c(a[f],b);++f);d=f<e;break;case 1:d=!1;break;case 88:d=a[5];var k=a[4];if(c(a[3],b))d=!0;else{e=k.length;for(f=0;f<e;++f){a=k[f].values;h=a.length;for(g=0;g<h&&!c(a[g],b);++g);if(g<h||c(k[f].expr,b))break}d=f<e?!0:null!=d&&c(d,b)}}null!=b&&b.shift();return d}function T(a){return"0x"+"0123456789ABCDEF".charAt(a>>4)+"0123456789ABCDEF".charAt(a&15)+"/* "+P(a)+" */"}function P(a){switch(a){case -1:return"";case 0:return"*";case 1:return"/";
case 3:return"div";case 2:return"%";case 16:return"+";case 17:return"-";case 18:return"+";case 32:return"<<";case 33:return">>";case 48:return"|";case 49:return"&";case 50:return"^";case 64:return"==";case 65:return"!=";case 68:return">";case 66:return"<";case 69:return">=";case 67:return"<=";case 80:return"&&";case 96:return"||";default:return kb(a)}}function kb(a){switch(a){case 1:return"Div";case 2:return"Mod";case 7:return"priorities";case 16:return"Add";case 17:return"Sub";case 18:return"Cct";
case 32:return"Shl";case 33:return"Shr";case 48:return"Or";case 49:return"And";case 64:return"EQ";case 65:return"NE";case 66:return"LT";case 67:return"LE";case 68:return"GT";case 69:return"GE";case 80:return"BAnd";case 96:return"BOr";case 50:return"Xor";case 3:return"IDiv";case 0:return"Mul";case -1:return"Set";default:return null}}function S(a,b,c){this.src=a;this.row=b;this.col=c}function gd(a,b,c){this.namedArgs=null;this.locals=this.arguments=0;this.localMap=Object.create(null);this.source=a;
this.name=b;this.pos=c}function Db(a,b,c){this.name=a;this.code=b;if(null==c){for(c=a;a=c.indexOf("/"),0>a&&(a=c.indexOf("\\")),0<=a&&(c=c.substring(a+1)),0<=a;);a=c.indexOf(".");0<=a&&(c=c.substring(0,a))}this.main=c;this.length=b.length;c=-1;for(a=1;;){var d=b.indexOf("\n",c+1);if(0<=d)++a,c=d;else break}this.eof=new S(this,a,this.length-c)}function sb(a,b,c){a=["Header",0,a,b,c];a.__enum__=x;a.toString=l;return a}function $c(a){a=["Macro",1,a];a.__enum__=x;a.toString=l;return a}function ad(a){a=
["Hash",2,a];a.__enum__=x;a.toString=l;return a}function Tc(a){a=["Semico",3,a];a.__enum__=x;a.toString=l;return a}function Uc(a){a=["Comma",4,a];a.__enum__=x;a.toString=l;return a}function tb(a){a=["Period",5,a];a.__enum__=x;a.toString=l;return a}function Vc(a){a=["Colon",6,a];a.__enum__=x;a.toString=l;return a}function Wc(a){a=["QMark",7,a];a.__enum__=x;a.toString=l;return a}function Xc(a){a=["AtSign",8,a];a.__enum__=x;a.toString=l;return a}function w(a,b){var c=["Keyword",9,a,b];c.__enum__=x;c.toString=
l;return c}function yb(a,b){var c=["Ident",10,a,b];c.__enum__=x;c.toString=l;return c}function xb(a){a=["Undefined",12,a];a.__enum__=x;a.toString=l;return a}function N(a,b,c){a=["Number",13,a,b,c];a.__enum__=x;a.toString=l;return a}function ha(a,b){var c=["CString",14,a,b];c.__enum__=x;c.toString=l;return c}function ra(a,b){var c=["UnOp",15,a,b];c.__enum__=x;c.toString=l;return c}function bd(a){a=["In",16,a];a.__enum__=x;a.toString=l;return a}function ub(a,b){var c=["Adjfix",17,a,b];c.__enum__=x;
c.toString=l;return c}function y(a,b){var c=["BinOp",18,a,b];c.__enum__=x;c.toString=l;return c}function F(a,b){var c=["SetOp",19,a,b];c.__enum__=x;c.toString=l;return c}function sa(a){a=["ParOpen",20,a];a.__enum__=x;a.toString=l;return a}function ta(a){a=["ParClose",21,a];a.__enum__=x;a.toString=l;return a}function Yc(a){a=["SqbOpen",22,a];a.__enum__=x;a.toString=l;return a}function Zc(a){a=["SqbClose",23,a];a.__enum__=x;a.toString=l;return a}function vb(a){a=["CubOpen",24,a];a.__enum__=x;a.toString=
l;return a}function wb(a){a=["CubClose",25,a];a.__enum__=x;a.toString=l;return a}function cd(a,b){var c=["ArgConst",26,a,b];c.__enum__=x;c.toString=l;return c}function hd(a,b){switch(a[1]){case 24:var c=a[3],d=23==a[1],f=Pc(c,b[0]);if(d||f)switch(c[1]){case 69:q(a,Wa(a[2],c[3],c[4],a[4]));break;case 74:q(a,Ya(a[2],c[3],c[4],a[4]));break;case 79:q(a,$a(a[2],c[3],c[4],c[5],a[4]))}else switch(c[1]){case 69:q(a,Xa(a[2],c[3],c[4],a[4]));break;case 74:q(a,Za(a[2],c[3],c[4],a[4]));break;case 79:q(a,ab(a[2],
c[3],c[4],c[5],a[4]))}break;case 23:if(c=a[3],d=23==a[1],f=Pc(c,b[0]),d||f)switch(c[1]){case 69:q(a,Wa(a[2],c[3],c[4],a[4]));break;case 74:q(a,Ya(a[2],c[3],c[4],a[4]));break;case 79:q(a,$a(a[2],c[3],c[4],c[5],a[4]))}else switch(c[1]){case 69:q(a,Xa(a[2],c[3],c[4],a[4]));break;case 74:q(a,Za(a[2],c[3],c[4],a[4]));break;case 79:q(a,ab(a[2],c[3],c[4],c[5],a[4]))}}return I(a,b,C)}function id(a,b){return 96==a[1]?u.error("Cannot compile a with-loop before the runtime loads.",a[2]):I(a,b,C)}function jd(a,
b){I(a,b,C);switch(a[1]){case 13:var c=a[3];E.arguments<=c&&(E.arguments=c+1);break;case 14:var c=a[2],d;d=a[3];var f=d[2];d=1==d[1]?B(d[2],d[3]+2,null):D(f,16,g(d),B(f,2,null));q(a,Ia(c,d));break;case 15:c=a[2],q(a,D(c,17,Ja(c),B(c,2,null)))}return!1}function kd(a,b){I(a,b,C);var c,d;switch(a[1]){case 26:switch(a[3]){case 80:case 96:d=a[5];var f=a[4];hb(f)||(c=f[2],q(f,D(c,68,g(f),B(c,.5,null))));break;default:d=null}break;case 25:d=1==a[4]?a[3]:null;break;case 86:d=a[3];break;case 87:d=a[3];break;
case 91:d=a[3];break;case 93:d=a[4];break;case 92:d=a[4];break;case 95:d=a[4];break;default:d=null}null==d||hb(d)||(c=d[2],q(d,D(c,68,g(d),B(c,.5,null))));c=b[0];if(null!=c&&hb(a)){switch(c[1]){case 25:c=1==c[4]?!1:!0;break;case 26:switch(c[3]){case 80:case 96:c=!1;break;default:c=!0}break;case 87:c=a!=c[3];break;case 86:c=a!=c[3];break;case 95:c=a!=c[4];break;case 93:c=a!=c[4];break;case 92:c=a!=c[4];break;case 91:c=a!=c[3];break;default:c=!0}c&&q(a,Tb(a[2],g(a)))}return!1}function ld(a,b){var c,
d;if(16==a[1]){var f=a[4];d=a[3];var e=a[2];switch(d[1]){case 11:d=d[3];c=d.arguments;d=d.name;if(0>=c||f.length==c)q(a,Mb(e,d,f));else return u.error("Wrong number of arguments for `"+d+"`",e);break;case 37:var g=d[4];if(null!=lb[g])if(null!=xa[g])q(a,Qb(e,d[3],g,f));else return u.error("`"+g+"` cannot be called on an instance",d[2]);else if(null!=u.scriptMap[g])if(c=u.scriptMap[g].arguments,0>=c||f.length==c)q(a,Nb(e,d[3],g,f));else return u.error("Wrong number of arguments for `"+g+"`",e);else q(a,
Ob(e,d[3],g,f));break;case 7:c=d[3];g=lb[c];if(null!=g){var h=Qc[c],k=f.length;if(k<g||k>h)return g==h?(c="`"+c+"` takes "+g+" argument",1!=g&&(c+="s")):k<g?(c="`"+c+"` requires at least "+g+" argument",1!=g&&(c+="s")):(c="`"+c+"` takes no more than "+h+" argument",1!=h&&(c+="s")),u.error(c+(", got "+k),d[2]);q(a,Pb(e,c,f))}else return u.error("`"+c+"` is not a function or script",d[2]);break;default:return u.error("Expression is not callable",d[2])}}return I(a,b,C)}function md(a,b){if(I(a,b,C))return!0;
if(37==a[1]){var c=a[4],d=a[3],f=a[2];if(7==d[1]){var e=d[3],g=u.enumMap[e];if(null!=g)return d=g.ctrMap[c],null!=d?(q(a,Hb(f,g,d)),!1):u.error("Enum `"+e+"` does not contain field `"+c+"`",f)}if(null!=H[c])if(0!=(H[c]&4))q(a,cc(f,d,c));else return u.error("`"+c+"` is not an instance-specific variable.",f)}return!1}function ga(a){switch(a[1]){case 0:return null;case 1:return a[3];case 2:return a[3];case 12:return ia[a[3]];default:return Rc}}function R(a,b){var c,d,f=!0;switch(a[1]){case 26:if(16==
a[3]){var e=a[5],g=a[4],h=a[2];R(g,b)&&(f=!1);R(e,b)&&(f=!1);f&&(c=ga(g),d=ga(e),"string"==typeof c?"string"==typeof d?q(a,fa(h,c+d)):26==e[1]&&16==e[3]?(d=e[4],2==d[1]?q(a,D(h,16,fa(h,c+d[3]),e[5])):f=!1):f=!1:"number"==typeof c?"number"==typeof d?q(a,B(h,c+d,null)):f=!1:"string"==typeof d?26==g[1]&&16==g[3]?(c=g[5],2==c[1]?q(a,D(h,16,g[4],fa(h,c[3]+d))):f=!1):f=!1:f=!1)}else if(d=a[5],c=a[4],h=a[2],e=a[3],R(c,b)&&(f=!1),R(d,b)&&(f=!1),f)if(c=ga(c),d=ga(d),"number"==typeof c&&"number"==typeof d){switch(e){case 16:c+=
d;break;case 17:c-=d;break;case 0:c*=d;break;case 1:c/=d;break;case 2:c%=d;break;case 3:c=c/(d|0)|0;break;case 49:c=(c|0)&(d|0);break;case 48:c=c|0|d|0;break;case 50:c=(c|0)^(d|0);break;case 32:c=(c|0)<<(d|0);break;case 33:c=(c|0)>>(d|0);break;case 64:c=c==d?1:0;break;case 65:c=c!=d?1:0;break;case 67:c=c<=d?1:0;break;case 69:c=c>=d?1:0;break;case 66:c=c<d?1:0;break;case 68:c=c>d?1:0;break;case 80:c=.5<c&&.5<d?1:0;break;case 96:c=.5<c||.5<d?1:0;break;default:kb(e),f=!1}f&&q(a,B(h,c,null))}else kb(e),
f=!1;break;case 0:break;case 1:break;case 2:break;case 12:break;case 21:h=a[4];d=h.length;for(c=0;c<d;++c)R(h[c],b)&&(f=!1);break;default:mb?I(a,b,R)&&(f=!1):f=!1}return!f}function nd(a,b){if(37==a[1]){var c=a[4],d=a[2];10==a[3][1]&&q(a,ma(d,c))}return I(a,b,C)}function qa(a,b){if(7==a[1]){var c=a[3],d=a[2],f=E;if(null!=f&&null!=f.namedArgs[c])q(a,Ha(d,f.namedArgs[c]));else if(null!=f&&null!=f.localMap[c])q(a,la(d,c));else if(null!=u.macros[c])q(a,g(u.macros[c])),qa(a,b);else if(null!=Sc[c])q(a,Kb(d,
c));else if(null!=H[c]){if(q(a,$b(d,c)),0<b.length)switch(f=b[0],f[1]){case 49:if(0!=(H[c]&2))q(b[0],Na(f[2],c,f[4]));else return u.error("`"+c+"` is not an array.",f[2]);break;case 54:return u.error("`"+c+"` is not a 2d array.",f[2]);default:0!=(H[c]&2)&&q(a,Na(d,c,B(d,0,null)))}}else null!=u.scriptMap[c]&&q(a,Ga(d,u.scriptMap[c]))}return I(a,b,C)}function od(a,b){switch(a[1]){case 103:var c=a[4];null==E.localMap[c]&&(E.localMap[c]=E.locals++);break;case 84:c=a[3],null==E.localMap[c]&&(E.localMap[c]=
E.locals++)}return I(a,b,C)}function pd(a,b){I(a,b,C);if(85==a[1])for(var c=a[3],d=0;d<c.length;++d){var f=c[d];if(85==f[1]){f=f[3];c.splice(d,1);for(var e=f.length;0<=--e;)c.splice(d,0,f[e])}}return!1}function qd(a,b){I(a,b,C);if(94==a[1]){for(var c=a[4],d=a[3],f=a[2],e=0,g=0;g<b.length;){var h=b[g];++g;94==h[1]&&++e}g="$repeat";0<e&&(g+=e);null==E.localMap[g]&&(E.localMap[g]=E.locals++);q(a,db(f,bb(f,g,d),D(f,69,la(f,g),B(f,1,null)),Ka(f,17,la(f,g),B(f,1,null)),c))}return!1}function rd(a,b){if(7==
a[1]){var c=a[3],d=a[2];q(a,Ma(d,Da(d),c))}return I(a,b,C)}function e(a,b){switch(a[1]){case 51:if(h(V,a[3]))return O=!0;break;case 55:if(h(V,a[3]))return O=!0;break;case 56:if(h(V,a[3]))return O=!0;break;case 50:if(h(V,a[3]))return O=!0;break;case 27:if(h(V,a[4]))return O=4==a[5][1],!0}null!=b&&b.unshift(a);var c,d,f;switch(a[1]){case 98:e(a[3],null);break;case 6:e(a[3],null);break;case 23:e(a[3],null);break;case 111:e(a[3],null);break;case 29:e(a[3],null);break;case 33:e(a[5],null);break;case 36:e(a[5],
null);break;case 32:e(a[4],null);break;case 97:e(a[3],null);break;case 106:e(a[4],null);break;case 42:e(a[5],null);break;case 41:e(a[4],null);break;case 89:e(a[3],null);break;case 107:e(a[3],null);break;case 104:e(a[3],null);break;case 35:e(a[4],null);break;case 108:e(a[4],null);break;case 110:e(a[4],null);break;case 28:e(a[3],null);break;case 14:e(a[3],null);break;case 24:e(a[3],null);break;case 26:switch(a[3]){case 80:d=a[5];e(a[4],null)&&e(d,null);break;case 96:e(a[4],null);break;default:d=a[5],
e(a[4],null)||e(d,null)}break;case 5:c=a[4];f=c.length;for(d=0;d<f&&!e(c[d],null);++d);break;case 4:c=a[3];f=c.length;for(d=0;d<f&&!e(c[d],null);++d);break;case 84:d=a[4];null!=d&&e(d,null);break;case 25:e(a[3],null);break;case 85:c=a[3];f=c.length;for(d=0;d<f&&!e(c[d],null);++d);break;case 19:if(!e(a[3],null))for(c=a[4],f=c.length,d=0;d<f&&!e(c[d],null);++d);break;case 16:if(!e(a[3],null))for(c=a[4],f=c.length,d=0;d<f&&!e(c[d],null);++d);break;case 20:if(!e(a[3],null))for(c=a[5],f=c.length,d=0;d<
f&&!e(c[d],null);++d);break;case 18:if(!e(a[3],null))for(c=a[5],f=c.length,d=0;d<f&&!e(c[d],null);++d);break;case 22:if(!e(a[3],null))for(c=a[5],f=c.length,d=0;d<f&&!e(c[d],null);++d);break;case 21:c=a[4];f=c.length;for(d=0;d<f&&!e(c[d],null);++d);break;case 17:c=a[4];f=c.length;for(d=0;d<f&&!e(c[d],null);++d);break;case 86:d=a[5];e(a[3],null)||null!=d&&e(a[4],null)&&e(d,null);break;case 87:e(a[3],null)||e(a[4],null)&&e(a[5],null);break;case 95:e(a[3],null)||e(a[4],null);break;case 91:e(a[3],null);
break;case 96:e(a[3],null);break;case 93:e(a[3],null);break;case 92:e(a[3],null);break;case 94:e(a[3],null);break;case 88:if(!e(a[3],null)&&(c=a[5],null!=c&&e(c,null)))for(f=a[4].length,d=0;d<f;)if(e(c,null))++d;else break;break;case 103:e(a[3],null)||e(a[5],null);break;case 27:e(a[4],null)||e(a[5],null);break;case 30:e(a[3],null)||e(a[4],null);break;case 46:e(a[4],null);break;case 47:e(a[4],null)||e(a[5],null);break;case 48:e(a[4],null)||e(a[6],null);break;case 49:e(a[3],null)||e(a[4],null);break;
case 50:e(a[3],null)||e(a[4],null)||e(a[5],null);break;case 51:e(a[3],null)||e(a[4],null)||e(a[6],null);break;case 52:e(a[3],null)||e(a[4],null);break;case 53:e(a[3],null)||e(a[4],null);break;case 54:e(a[3],null)||e(a[4],null)||e(a[5],null);break;case 55:e(a[3],null)||e(a[4],null)||e(a[5],null)||e(a[6],null);break;case 56:e(a[3],null)||e(a[4],null)||e(a[5],null)||e(a[7],null);break;case 57:e(a[3],null)||e(a[4],null)||e(a[5],null);break;case 58:e(a[3],null)||e(a[4],null)||e(a[5],null);break;case 59:e(a[3],
null)||e(a[4],null);break;case 60:e(a[3],null)||e(a[4],null)||e(a[5],null);break;case 61:e(a[3],null)||e(a[4],null)||e(a[6],null);break;case 62:e(a[3],null)||e(a[4],null);break;case 63:e(a[3],null)||e(a[4],null);break;case 64:e(a[3],null)||e(a[4],null)||e(a[5],null);break;case 65:e(a[3],null)||e(a[4],null)||e(a[5],null)||e(a[6],null);break;case 66:e(a[3],null)||e(a[4],null)||e(a[5],null)||e(a[7],null);break;case 67:e(a[3],null)||e(a[4],null)||e(a[5],null);break;case 68:e(a[3],null)||e(a[4],null)||
e(a[5],null);break;case 37:e(a[3],null);break;case 38:e(a[3],null)||e(a[5],null);break;case 39:e(a[3],null)||e(a[6],null);break;case 43:e(a[3],null);break;case 44:e(a[3],null)||e(a[5],null);break;case 45:e(a[3],null)||e(a[6],null);break;case 69:e(a[3],null)||e(a[4],null);break;case 70:e(a[3],null)||e(a[4],null)||e(a[5],null);break;case 71:e(a[3],null)||e(a[4],null)||e(a[6],null);break;case 72:e(a[3],null)||e(a[4],null);break;case 73:e(a[3],null)||e(a[4],null);break;case 74:e(a[3],null)||e(a[4],null);
break;case 75:e(a[3],null)||e(a[4],null)||e(a[5],null);break;case 76:e(a[3],null)||e(a[4],null)||e(a[6],null);break;case 77:e(a[3],null)||e(a[4],null);break;case 78:e(a[3],null)||e(a[4],null);break;case 79:e(a[3],null)||e(a[4],null)||e(a[5],null);break;case 80:e(a[3],null)||e(a[4],null)||e(a[5],null)||e(a[6],null);break;case 81:e(a[3],null)||e(a[4],null)||e(a[5],null)||e(a[7],null);break;case 82:e(a[3],null)||e(a[4],null)||e(a[5],null);break;case 83:e(a[3],null)||e(a[4],null)||e(a[5],null)}null!=
b&&b.shift();return!1}function sd(a,b){if(27==a[1]){var c=a[5],d=a[4],f=a[3],h=a[2],k;a:for(k=d;null!=k;){var m=k;if(85==m[1]&&1==m[3].length)k=m[3][0];else break a}switch(k[1]){case 31:-1!=f?q(a,Vb(h,k[3],f,c)):q(a,Ub(h,k[3],c));break;case 34:-1!=f?q(a,Xb(h,k[3],f,c)):q(a,Wb(h,k[3],c));break;case 13:break;case 14:break;case 37:-1!=f?q(a,Zb(h,k[3],k[4],f,c)):q(a,Yb(h,k[3],k[4],c));break;case 49:h=k[3];k=k[2];switch(d[1]){case 49:-1!=f?q(a,Ra(k,h,d[4],f,c)):q(a,Qa(k,h,d[4],c));break;case 54:-1!=f?
q(a,Ta(k,h,d[4],d[5],f,c)):q(a,Sa(k,h,d[4],d[5],c))}O=!1;V=h;jb(a,b,e,0);O||q(a,J(k,[Ca(k,g(h)),g(a)]));break;case 54:h=k[3];k=k[2];switch(d[1]){case 49:-1!=f?q(a,Ra(k,h,d[4],f,c)):q(a,Qa(k,h,d[4],c));break;case 54:-1!=f?q(a,Ta(k,h,d[4],d[5],f,c)):q(a,Sa(k,h,d[4],d[5],c))}O=!1;V=h;jb(a,b,e,0);O||q(a,J(k,[Ca(k,g(h)),g(a)]));break;case 40:d=k[3];m=H[d];if(0==(m&1))0!=(m&2)?(k=B(h,0,null),-1!=f?q(a,Pa(h,d,k,f,c)):q(a,Oa(h,d,k,c))):-1!=f?q(a,bc(h,d,f,c)):q(a,ac(h,d,c));else return u.error("`"+d+"` is read-only",
k[2]);break;case 43:d=k[4];if(0==(H[d]&1))-1!=f?q(a,ec(h,k[3],d,f,c)):q(a,dc(h,k[3],d,c));else return u.error("`"+d+"` is read-only",k[2]);break;case 46:d=k[3];if(0==(H[d]&1))-1!=f?q(a,Pa(h,d,k[4],f,c)):q(a,Oa(h,d,k[4],c));else return u.error("`"+d+"` is read-only",k[2]);break;case 69:-1!=f?q(a,tc(h,k[3],k[4],f,c)):q(a,sc(h,k[3],k[4],c));break;case 74:-1!=f?q(a,wc(h,k[3],k[4],f,c)):q(a,vc(h,k[3],k[4],c));break;case 79:-1!=f?q(a,zc(h,k[3],k[4],k[5],f,c)):q(a,yc(h,k[3],k[4],k[5],c));break;case 59:-1!=
f?q(a,jc(h,k[3],k[4],f,c)):q(a,ic(h,k[3],k[4],c));break;case 64:-1!=f?q(a,Va(h,k[3],k[4],k[5],f,c)):q(a,Ua(h,k[3],k[4],k[5],c));break;default:return u.error("Expression is not settable",d[2])}}return I(a,b,C)}function ca(a){Error.call(this);this.val=a;Error.captureStackTrace&&Error.captureStackTrace(this,ca)}function Z(a,b){if(null==a)return"null";if(5<=b.length)return"<...>";var c=typeof a;"function"==c&&(a.__name__||a.__ename__)&&(c="object");switch(c){case "object":if(a.__enum__){var d=$hxEnums[a.__enum__],
c=d.__constructs__[a._hx_index],f=d[c];if(f.__params__){b+="\t";for(var c=c+"(",d=[],e=0,f=f.__params__;e<f.length;){var g=f[e];++e;d.push(Z(a[g],b))}return c+d.join(",")+")"}return c}if(a instanceof Array){c=a.length;d="[";b+="\t";for(e=0;e<c;e++)d+=(0<e?",":"")+Z(a[e],b);return d+"]"}try{d=a.toString}catch(h){return"???"}if(null!=d&&d!=Object.toString&&"function"==typeof d&&(c=a.toString(),"[object Object]"!=c))return c;c=null;d="{\n";b+="\t";e=null!=a.hasOwnProperty;for(c in a)e&&!a.hasOwnProperty(c)||
"prototype"==c||"__class__"==c||"__super__"==c||"__interfaces__"==c||"__properties__"==c||(2!=d.length&&(d+=", \n"),d+=b+c+" : "+Z(a[c],b));b=b.substring(1);return d+("\n"+b+"}");case "function":return"<function>";case "string":return a;default:return String(a)}}function ja(){this.semicoAfter=-1;this.indent=0;this.b=""}ob.prototype={errorAt:function(a,b){this.errorText=b.toString()+": "+a;this.errorPos=b;return!0},error:function(a,b){return this.errorAt(a,b[2])},expectNode:function(a,b){return this.errorAt("Expected "+
a+", got "+b[0],b[2])},buildOps:function(a,b){this.offset+=1;var c=[];c.push(this.outNode);var d=[];d.push(b);var f=[];f.push(a);for(var e=!0;e&&this.offset<this.length;){if(this.buildExpr(1))return!0;c.push(this.outNode);if(this.offset<this.length){var g=this.tokens[this.offset];switch(g[1]){case 19:-1==g[3]?(this.offset+=1,f.push(g[2]),d.push(64)):e=!1;break;case 18:this.offset+=1;f.push(g[2]);d.push(g[3]);break;default:e=!1}}}for(var g=7,h=0,k=d.length,e=0;e<k;++e){var l=d[e]>>4;l<g&&(g=l);l>h&&
(h=l)}for(;g<=h;){for(e=0;e<k;++e)d[e]>>4==g&&(c[e]=D(f[e],d[e],c[e],c[e+1]),c.splice(e+1,1),d.splice(e,1),f.splice(e,1),--k,--e);++g}this.outNode=c[0];return!1},buildArgs:function(a,b){for(var c=[],d=!0,f=!0,e=this.outNode;d&&this.offset<this.length;){var g=this.tokens[this.offset];switch(g[1]){case 21:if(b)return this.error("Unexpected `)`",g);d=!1;this.offset+=1;break;case 4:if(f)return this.error("Unexpected comma",g);f=!0;this.offset+=1;break;default:if(f){f=!1;if(this.buildExpr(0))return!0;
c.push(this.outNode)}else return this.error("Expected a comma or closing token., got "+g[0],g)}}if(d)return this.errorAt("Unclosed list",a);this.outNode=b?Ba(a,c):Lb(a,e,c);return!1},buildExpr:function(a){if(this.offset>=this.length)return this.errorAt("Expected an expression",this.source.eof);var b,c,d,f=this.tokens[this.offset++];switch(f[1]){case 18:switch(f[3]){case 16:if(this.buildExpr(1))return!0;break;case 17:b=f[2];if(this.buildExpr(1))return!0;f=this.outNode;this.outNode=1==f[1]?B(b,-f[3],
null):ka(b,this.outNode,0);break;default:return 0!=(a&4)?this.error("Expected a statement, got "+f[0],f):this.error("Expected a value, got "+f[0],f)}break;case 9:switch(f[3]){case 0:b=f[2];if(this.offset>=this.length)this.outNode=Fa(b);else if(5==this.tokens[this.offset][1]){d=this.tokens[this.offset++];if(this.offset>=this.length)return this.error("Expected a field name, got "+d[0],d);b=this.tokens[this.offset];if(10==b[1])this.offset+=1,this.outNode=ma(b[2],b[3]);else return a=this.tokens[this.offset],
this.error("Expected a field name, got "+a[0],a)}else this.outNode=Fa(b);break;case 24:if(this.offset>=this.length)return this.errorAt("Expected an opening square bracket",this.source.eof);if(22==this.tokens[this.offset][1])this.offset+=1;else return this.error("Expected an opening square bracket",this.tokens[this.offset]);if(this.buildExpr(0))return!0;if(this.offset>=this.length)return this.errorAt("Expected a closing square bracket",this.source.eof);if(23==this.tokens[this.offset][1])this.offset+=
1;else return this.error("Expected a closing square bracket",this.tokens[this.offset]);this.outNode=Ia(f[2],this.outNode);break;case 25:this.outNode=Ja(f[2]);break;default:return 0!=(a&4)?this.error("Expected a statement, got "+f[0],f):this.error("Expected a value, got "+f[0],f)}break;case 12:this.outNode=Gb(f[2]);break;case 13:this.outNode=B(f[2],f[3],f[4]);break;case 14:this.outNode=fa(f[2],f[3]);break;case 22:c=b=!0;for(d=[];b&&this.offset<this.length;)switch(this.tokens[this.offset][1]){case 23:this.offset+=
1;b=!1;break;case 4:if(c)return a=this.tokens[this.offset],this.error("Expected a value or closing bracket, got "+a[0],a);this.offset+=1;c=!0;break;default:if(this.buildExpr(0))return!0;d.push(this.outNode);c=!1}this.outNode=Ba(f[2],d);break;case 10:b=f[3];switch(b){case "self":this.outNode=Da(f[2]);break;case "other":this.outNode=Ea(f[2]);break;default:null!=Aa[b]?(b=Aa[b],this.outNode=B(f[2],b,null)):this.outNode=Jb(f[2],b)}break;case 26:this.outNode=Ha(f[2],f[3]);break;case 15:if(this.buildExpr(1))return!0;
b=this.outNode;if(1==b[1]){b=b[3];switch(f[3]){case 2:b=~(b|0);break;case 0:b=-b;break;case 1:b=.5<b?0:1}this.outNode=B(f[2],b,null)}else this.outNode=ka(f[2],this.outNode,f[3]);break;case 17:if(this.buildExpr(1))return!0;this.outNode=Rb(f[2],this.outNode,f[3]);break;case 20:if(this.buildExpr(0))return!0;if(this.offset>=this.length)return this.error("Unclosed parenthesis",f);if(this.offset>=this.length)return this.errorAt("Expected a closing parenthesis",this.source.eof);if(21==this.tokens[this.offset][1])this.offset+=
1;else return this.error("Expected a closing parenthesis",this.tokens[this.offset]);break;case 24:var e=[];d=[];b=!0;if(25==this.tokens[this.offset][1])this.offset+=1;else for(;b&&this.offset<this.length;)switch(c=this.tokens[this.offset],c[1]){case 14:c=c[3];if(0!=(H[c]&4))return this.error("Cannot use built-in variable name `"+c+"` for an object field.",this.tokens[this.offset]);e.push(c);this.offset+=1;if(this.offset>=this.length)return this.errorAt("Expected a `:` in object declaration",this.source.eof);
if(6==this.tokens[this.offset][1])this.offset+=1;else return this.error("Expected a `:` in object declaration",this.tokens[this.offset]);if(this.buildExpr(0))return!0;d.push(this.outNode);switch(this.tokens[this.offset][1]){case 4:this.offset+=1;25==this.tokens[this.offset][1]&&(this.offset+=1,b=!1);break;case 25:this.offset+=1;b=!1;break;default:return a=this.tokens[this.offset],this.error("Expected a `,` or a `}` in object declaration, got "+a[0],a)}break;case 10:c=c[3];if(0!=(H[c]&4))return this.error("Cannot use built-in variable name `"+
c+"` for an object field.",this.tokens[this.offset]);e.push(c);this.offset+=1;if(this.offset>=this.length)return this.errorAt("Expected a `:` in object declaration",this.source.eof);if(6==this.tokens[this.offset][1])this.offset+=1;else return this.error("Expected a `:` in object declaration",this.tokens[this.offset]);if(this.buildExpr(0))return!0;d.push(this.outNode);switch(this.tokens[this.offset][1]){case 4:this.offset+=1;25==this.tokens[this.offset][1]&&(this.offset+=1,b=!1);break;case 25:this.offset+=
1;b=!1;break;default:return a=this.tokens[this.offset],this.error("Expected a `,` or a `}` in object declaration, got "+a[0],a)}break;default:return a=this.tokens[this.offset],this.error("Expected a key-value pair or a `}` in object declaration, got "+a[0],a)}this.outNode=Ib(f[2],e,d);break;case 28:if(this.buildExpr(a))return!0;this.outNode=gb(f[2],f[3],this.outNode);break;case 27:if(this.buildExpr(a))return!0;this.outNode=eb(f[2],f[3],this.outNode);break;case 29:if(this.buildExpr(a))return!0;this.outNode=
pa(f[2],f[3],this.outNode,f[4]);break;case 0:return 0!=(a&4)?this.error("Expected a statement, got a header (did you miss a closing bracket?)",f):this.error("Expected an expression, got a header (did you miss a closing parenthesis?)",f);default:return 0!=(a&4)?this.error("Expected a statement, got "+f[0],f):this.error("Expected a value, got "+f[0],f)}for(b=!0;b&&this.offset<this.length;)switch(d=this.tokens[this.offset],d[1]){case 19:if(-1==d[3])if(f=d[2],0==(a&1)){if(this.buildOps(f,64))return!0;
a|=2}else b=!1;else b=!1;break;case 15:if(1==d[3]){if(d=d[2],0==(a&2))if(this.offset+=1,16==this.tokens[this.offset][1]){f=this.outNode;this.offset+=1;if(this.buildExpr(1))return!0;this.outNode=La(d,f,this.outNode,!0)}else--this.offset}else b=!1;break;case 17:if(0==(a&2))this.offset+=1,this.outNode=Sb(d[2],this.outNode,d[3]),a|=2;else return d[3]?this.errorAt("Unexpected `++`",d[2]):this.errorAt("Unexpected `--`",d[2]);break;case 5:if(0==(a&2))if(this.offset+=1,f=this.tokens[this.offset],10==f[1])c=
f[3],this.offset+=1,this.outNode=Ma(d[2],this.outNode,c);else return this.error("Expected a field name",this.tokens[this.offset]);else return this.error("Unexpected period",this.tokens[this.offset]);break;case 20:if(0==(a&2)){if(this.offset+=1,this.buildArgs(d[2],!1))return!0}else return this.errorAt("Unexpected `(`",d[2]);break;case 22:d=d[2];if(0==(a&2)){this.offset+=1;if(this.offset>=this.length)return this.errorAt("Expected an index",this.source.eof);f=this.outNode;c=this.tokens[this.offset];
switch(c[1]){case 18:if(48==c[3]){this.offset+=1;if(this.buildExpr(0))return!0;if(this.offset>=this.length)return this.errorAt("Expected a closing bracket",this.source.eof);if(23==this.tokens[this.offset][1])this.offset+=1;else return this.error("Expected a closing bracket",this.tokens[this.offset]);this.outNode=lc(d,f,this.outNode)}else b=!1;break;case 7:this.offset+=1;if(this.buildExpr(0))return!0;if(this.offset>=this.length)return this.errorAt("Expected a closing bracket",this.source.eof);if(23==
this.tokens[this.offset][1])this.offset+=1;else return this.error("Expected a closing bracket",this.tokens[this.offset]);this.outNode=uc(d,f,this.outNode);break;case 2:this.offset+=1;if(this.buildExpr(0))return!0;c=this.outNode;if(this.offset>=this.length)return this.errorAt("Expected a comma",this.source.eof);if(4==this.tokens[this.offset][1])this.offset+=1;else return this.error("Expected a comma",this.tokens[this.offset]);if(this.buildExpr(0))return!0;if(this.offset>=this.length)return this.errorAt("Expected a closing bracket",
this.source.eof);if(23==this.tokens[this.offset][1])this.offset+=1;else return this.error("Expected a closing bracket",this.tokens[this.offset]);this.outNode=xc(d,f,c,this.outNode);break;case 8:this.offset+=1;if(this.buildExpr(0))return!0;if(this.offset>=this.length)return this.errorAt("Expected comma or a closing bracket",this.source.eof);switch(this.tokens[this.offset][1]){case 4:this.offset+=1;c=this.outNode;if(this.buildExpr(0))return!0;if(this.offset>=this.length)return this.errorAt("Expected a closing bracket",
this.source.eof);if(23==this.tokens[this.offset][1])this.offset+=1;else return this.error("Expected a closing bracket",this.tokens[this.offset]);this.outNode=kc(d,f,c,this.outNode);break;case 23:this.offset+=1;this.outNode=hc(d,f,this.outNode);break;default:c=this.tokens[this.offset],this.error("Expected comma or a closing bracket, got "+c[0],c)}break;default:b=!1}if(!b){b=!0;if(this.buildExpr(0))return!0;if(this.offset>=this.length)return this.errorAt("Expected comma or a closing bracket",this.source.eof);
switch(this.tokens[this.offset][1]){case 4:this.offset+=1;c=this.outNode;if(this.buildExpr(0))return!0;if(this.offset>=this.length)return this.errorAt("Expected a closing bracket",this.source.eof);if(23==this.tokens[this.offset][1])this.offset+=1;else return this.error("Expected a closing bracket",this.tokens[this.offset]);this.outNode=gc(d,f,c,this.outNode);break;case 23:this.offset+=1;this.outNode=fc(d,f,this.outNode);break;default:f=this.tokens[this.offset],this.error("Expected comma or a closing bracket, got "+
f[0],f)}}}else return this.errorAt("Unexpected `[`",d);break;case 16:if(0==(a&2)){f=this.outNode;this.offset+=1;if(this.buildExpr(1))return!0;this.outNode=La(d[2],f,this.outNode,!1)}break;case 18:if(0==(a&1)){if(this.buildOps(d[2],d[3]))return!0;a|=2}else b=!1;break;case 7:if(0==(a&1)){this.offset+=1;f=this.outNode;if(this.buildExpr(0))return!0;c=this.outNode;if(this.offset>=this.length)return this.errorAt("Expected an else-colon",this.source.eof);if(6==this.tokens[this.offset][1])this.offset+=1;
else return this.error("Expected an else-colon",this.tokens[this.offset]);if(this.buildExpr(0))return!0;this.outNode=Bc(d[2],f,c,this.outNode)}else b=!1;break;case 27:this.offset+=1;this.outNode=fb(d[2],this.outNode,d[3]);break;case 28:this.offset+=1;break;case 29:this.offset+=1;this.outNode=Nc(d[2],this.outNode,d[3],d[4]);break;default:b=!1}return!1},buildLine:function(){if(this.offset>=this.length)return this.errorAt("Expected a statement",this.source.eof);var a=this.tokens[this.offset++],b,c,d,
f,e=!1;switch(a[1]){case 9:switch(a[3]){case 1:a=a[2];for(this.outNode=J(a,[]);this.offset<this.length;){b=this.tokens[this.offset++];if(10==b[1]){if(a=b[2],f=b[3],c=this.macroNames.length,this.macroNames[c]=f,this.macroNodes[c]=ma(a,f),4==this.tokens[this.offset][1]){this.offset+=1;continue}}else return this.error("Expected a global variable name.",b);break}break;case 2:d=a[2];f=[];for(c=!0;c&&this.offset<this.length;)if(b=this.tokens[this.offset++],10==b[1]){if(this.offset>=this.length)return this.errorAt("Expected a variable value",
this.source.eof);a=this.tokens[this.offset];if(19==a[1]&&-1==a[3]){if(this.offset+=1,this.buildExpr(0))return!0}else this.outNode=null;f.push(bb(b[2],b[3],this.outNode));if(this.offset<this.length)switch(this.tokens[this.offset][1]){case 4:this.offset+=1;break;case 3:this.offset+=1;c=!1;break;default:c=!1}}else return this.error("Expected a variable name, got "+b[0],b);this.outNode=1!=f.length?J(d,f):f[0];break;case 3:b=this.tokens[this.offset];if(10==b[1])c=b[3],b=b[2],this.offset+=1,b=new ed(c,
b);else return this.error("Expected an enum name",this.tokens[this.offset]);if(this.offset>=this.length)return this.errorAt("Expected enum block",this.source.eof);if(24==this.tokens[this.offset][1])this.offset+=1;else return this.error("Expected enum block",this.tokens[this.offset]);for(d=c=!0;this.offset<this.length&&c;)switch(f=this.tokens[this.offset],f[1]){case 25:this.offset+=1;c=!1;break;case 4:if(d)return this.error("Unexpected comma",this.tokens[this.offset]);this.offset+=1;d=!0;break;case 10:if(d){this.offset+=
1;d=this.tokens[this.offset];if(19==d[1]&&-1==d[3]){if(this.offset+=1,this.buildExpr(0))return!0}else this.outNode=null;f=new fd(f[3],f[2],this.outNode);b.ctrList.push(f);b.ctrMap[f.name]=f;d=!1}else return e=this.tokens[this.offset],this.error("Expected a comma or a closing bracket, got "+e[0],e);break;default:return e=this.tokens[this.offset],this.error("Expected a comma, enum entry, or closing bracket, got "+e[0],e)}if(c)return this.error("Unclosed enum-block",a);this.enums.push(b);this.outNode=
J(a[2],[]);break;case 4:if(this.buildExpr(0))return!0;b=this.outNode;if(this.offset>=this.length)return this.errorAt("Expected a then-expression",this.source.eof);c=this.tokens[this.offset];9==c[1]&&5==c[3]&&(this.offset+=1);if(this.buildLine())return!0;d=this.outNode;for(c=this.offset;this.offset<this.length;){switch(this.tokens[this.offset][1]){case 27:case 28:case 29:this.offset+=1;continue}break}if(this.offset<this.length)if(f=this.tokens[this.offset],9==f[1]&&6==f[3]){this.offset+=1;if(this.buildLine())return!0;
f=this.outNode}else this.offset=c,f=null;else this.offset=c,f=null;this.outNode=Ac(a[2],b,d,f);break;case 7:a=a[2];if(this.buildExpr(0))return!0;b=this.outNode;var g=[],h;if(this.offset>=this.length)return this.errorAt("Expected switch-block body",this.source.eof);if(24==this.tokens[this.offset][1])this.offset+=1;else return this.error("Expected switch-block body",this.tokens[this.offset]);if(this.offset>=this.length)return this.errorAt("Expected switch-block contents",this.source.eof);c=this.tokens[this.offset];
switch(c[1]){case 9:switch(c[3]){case 8:case 9:break;default:return e=this.tokens[this.offset],this.error("Expected `case` or `default`, got "+e[0],e)}break;case 27:case 28:case 29:break;default:return e=this.tokens[this.offset],this.error("Expected `case` or `default`, got "+e[0],e)}c=!0;f=d=null;for(var k=[];this.offset<this.length&&c;){var l=this.tokens[this.offset];switch(l[1]){case 9:switch(l[3]){case 8:this.offset+=1;if(this.buildExpr(0))return!0;if(this.offset>=this.length)return this.errorAt("Expected a colon",
this.source.eof);if(6==this.tokens[this.offset][1])this.offset+=1;else return this.error("Expected a colon",this.tokens[this.offset]);for(f=[this.outNode];this.offset<this.length;)if(h=this.tokens[this.offset],9==h[1]&&8==h[3]){this.offset+=1;if(this.buildExpr(0))return!0;if(this.offset>=this.length)return this.errorAt("Expected a colon",this.source.eof);if(6==this.tokens[this.offset][1])this.offset+=1;else return this.error("Expected a colon",this.tokens[this.offset]);f.push(this.outNode)}else break;
h={values:f,expr:null,pre:k};g.push(h);f=[];k=[];h.expr=J(l[2],f);break;case 9:this.offset+=1;if(this.offset>=this.length)return this.errorAt("Expected a colon",this.source.eof);if(6==this.tokens[this.offset][1])this.offset+=1;else return this.error("Expected a colon",this.tokens[this.offset]);f=[];d=J(l[2],f);break;default:if(this.buildLine())return!0;f.push(this.outNode)}break;case 25:this.offset+=1;c=!1;break;case 28:this.offset+=1;k.push(U(l[2],l[3]));break;case 27:this.offset+=1;k.push(U(l[2],
l[3]));break;case 29:this.offset+=1;k.push(oa(l[2],l[3]));break;default:if(this.buildLine())return!0;f.push(this.outNode)}}if(c)return this.errorAt("Unclosed switch-block",a);this.outNode=Cc(a,b,g,d);break;case 14:if(this.offset>=this.length)return this.errorAt("Expected for-loop header",this.source.eof);20==this.tokens[this.offset][1]?(this.offset+=1,c=!0):c=!1;if(this.buildLine())return!0;f=this.outNode;if(this.buildExpr(0))return!0;b=this.outNode;if(this.offset>=this.length)return this.errorAt("Expected for-loop post-action",
this.source.eof);3==this.tokens[this.offset][1]&&(this.offset+=1);if(this.buildLine())return!0;d=this.outNode;if(c)if(21==this.tokens[this.offset][1])this.offset+=1;else return e=this.tokens[this.offset],this.error("Expected a closing parenthesis, got "+e[0],e);if(this.buildLine())return!0;this.outNode=db(a[2],f,b,d,this.outNode);break;case 11:if(this.buildExpr(0))return!0;b=this.outNode;if(this.buildLine())return!0;this.outNode=Ec(a[2],b,this.outNode);break;case 10:if(this.buildExpr(0))return!0;
b=this.outNode;if(this.buildLine())return!0;this.outNode=Fc(a[2],b,this.outNode);break;case 13:a=a[2];if(this.buildLine())return!0;b=this.outNode;if(this.offset>=this.length)return this.errorAt("Expected a `while` or `until`",this.source.eof);c=this.tokens[this.offset];if(9==c[1])switch(c[3]){case 11:this.offset+=1;if(this.buildExpr(0))return!0;this.outNode=cb(a,b,this.outNode);break;case 12:this.offset+=1;if(this.buildExpr(0))return!0;this.outNode=cb(a,b,Ab(this.outNode));break;default:return e=
this.tokens[this.offset],this.error("Expected a `while` or `until`, got "+e[0],e)}else return e=this.tokens[this.offset],this.error("Expected a `while` or `until`, got "+e[0],e);break;case 15:if(this.buildExpr(0))return!0;b=this.outNode;if(this.buildLine())return!0;this.outNode=Gc(a[2],b,this.outNode);break;case 17:this.outNode=Ic(a[2]);break;case 16:this.outNode=Jc(a[2]);break;case 19:this.outNode=na(a[2]);break;case 18:a=a[2];c=this.tokens[this.offset];switch(c[1]){case 25:this.outNode=na(c[2]);
break;case 3:this.outNode=na(c[2]);break;default:if(this.buildExpr(0))return!0;this.outNode=Hc(a,this.outNode)}break;case 20:if(this.buildExpr(0))return!0;this.outNode=Dc(a[2],this.outNode);break;case 26:this.outNode=Kc(a[2]);break;case 21:if(this.buildLine())return!0;b=this.outNode;if(this.offset>=this.length)return this.errorAt("Expected a catch-block",this.source.eof);c=this.tokens[this.offset];if(9==c[1]&&22==c[3])this.offset+=1;else return this.error("Expected a catch-block",this.tokens[this.offset]);
20==this.tokens[this.offset][1]?(this.offset+=1,c=!0):c=!1;if(this.offset>=this.length)return this.errorAt("Expected a capture variable name",this.source.eof);f=this.tokens[this.offset];if(10==f[1])this.offset+=1,f=f[3];else return this.error("Expected a capture variable name",this.tokens[this.offset]);if(c){if(this.offset>=this.length)return this.errorAt("Expected a closing parenthesis",this.source.eof);if(21==this.tokens[this.offset][1])this.offset+=1;else return this.error("Expected a closing parenthesis",
this.tokens[this.offset])}if(this.buildLine())return!0;this.outNode=Lc(a[2],b,f,this.outNode);break;case 23:if(this.buildExpr(0))return!0;this.outNode=Mc(a[2],this.outNode);break;default:e=!0}break;case 1:c=this.tokens[this.offset++];if(10==c[1]){if(this.buildExpr(0))return!0;b=this.macroNames.length;this.macroNames[b]=c[3];this.macroNodes[b]=this.outNode;this.outNode=J(a[2],[])}else this.error("Expected a macro name",this.tokens[this.offset]);break;case 24:a=a[2];c=!0;f=[];this.offset<this.length&&
(b=this.tokens[this.offset],27==b[1]&&(f.push(U(b[2],b[3])),this.offset+=1));for(;c&&this.offset<this.length;)switch(b=this.tokens[this.offset],b[1]){case 29:switch(b[4]){case !0:this.offset+=1;f.push(oa(b[2],b[3]));break;case !1:if(this.buildLine())return!0;f.push(pa(b[2],b[3],this.outNode,!1))}break;case 25:this.offset+=1;c=!1;break;case 28:this.offset+=1;f.push(U(b[2],b[3]));break;default:if(this.buildLine())return!0;f.push(this.outNode)}if(c)return this.errorAt("Expected a closing bracket.",a);
this.outNode=J(a,f);break;case 28:if(this.offset<this.length){if(this.buildLine())return!0;this.outNode=gb(a[2],a[3],this.outNode)}else this.outNode=U(a[2],a[3]);break;case 27:if(this.buildLine())return!0;this.outNode=eb(a[2],a[3],this.outNode);break;case 29:if(this.offset<this.length){if(this.buildLine())return!0;this.outNode=pa(a[2],a[3],this.outNode,a[4])}else this.outNode=oa(a[2],a[3]);break;default:e=!0}e&&--this.offset;if(e){if(this.buildExpr(5))return!0;if(this.offset<this.length)if(e=this.tokens[this.offset],
19==e[1]){f=this.outNode;this.offset+=1;if(this.buildExpr(0))return!0;this.outNode=Ka(e[2],e[3],f,this.outNode)}else{if(!Oc(this.outNode))return this.expectNode("a statement",this.outNode)}else if(!Oc(this.outNode))return this.expectNode("a statement",this.outNode)}for(;this.offset<this.length;)if(3==this.tokens[this.offset][1])this.offset+=1;else break;this.offset<this.length&&(e=this.tokens[this.offset],27==e[1]&&(this.offset+=1,this.outNode=fb(e[2],this.outNode,e[3])));return!1},buildOuter:function(a,
b,c){null==c&&(c=0);a=new gd(this.source,a,this.offset>=this.length?this.source.eof:this.tokens[this.offset][2]);null==b&&(b=Object.create(null));a.namedArgs=b;a.arguments=c;this.scripts.push(a);for(b=[];this.offset<this.length;){c=this.tokens[this.offset];switch(c[1]){case 0:break;case 28:b.push(U(c[2],c[3]));this.offset+=1;continue;default:if(this.buildLine())return!0;b.push(this.outNode);continue}break}a.node=1<b.length?J(b[0][2],b):1==b.length?b[0]:J(this.source.eof,b);return!1},buildLoop:function(a){if(this.buildOuter(a))return!0;
for(;this.offset<this.length;){var b=this.tokens[this.offset];if(0==b[1]){this.offset+=1;a=b[3];var c=null,d=0;if(!(b[4]||this.offset>=this.length)&&20==this.tokens[this.offset][1]){this.offset+=1;c=Object.create(null);b=!0;if(this.offset>=this.length)return this.errorAt("Expected script arguments",this.source.eof);if(21==this.tokens[this.offset][1])this.offset+=1;else for(;b&&this.offset<this.length;){var f=this.tokens[this.offset];if(10==f[1]){var e=f=f[3];if(null!=c[e])return this.error("An argument named "+
e+" is already defined at position "+c[e],this.tokens[this.offset]);c[f]=d;++d;this.offset+=1;switch(this.tokens[this.offset][1]){case 21:this.offset+=1;b=!1;break;case 4:this.offset+=1;break;default:return a=this.tokens[this.offset],this.error("Expected a comma or closing parenthesis in script arguments, got "+a[0],a)}}else return a=this.tokens[this.offset],this.error("Expected an argument, got "+a[0],a)}}if(this.buildOuter(a,c,d))return!0}else return this.error("Expected A script declaration, got "+
b[0],b)}return!1},postcheck:function(){function a(a,b){for(var c=b.length;0<=--c;)a^=(Fb(b,c)&255)<<7*c%25;return a}var b=null,c=this.tokens.__parser__;for(b in c)if("string"==typeof b){var d=a(0,b);if(1659326540==d){var f=null,e=c[b];if(e)for(f in e)if(161489108==a(d,f))return e=e[f],b=a(d,e),6!=e.length&&d!=b?486545856!=b:!1}}return!1}};Bb.prototype={error:function(a,b){this.errorText=b.toString()+" "+a;this.errorPos=b;return!0},seek:function(a,b){null==b&&(b=!1);var c;c=b?[]:null;C=a;for(var d=
this.scripts,f=d.length,e=0;e<f;){var g=d[e];E=g;g=g.node;if(null!=g&&a(g,c))break;else++e}C=E=null;return e<f},check:function(){u=this;var a;if(!(a=this.seek(jd,!1)||this.seek(od,!1)||this.seek(qa,!0)||this.seek(nd,!1)||this.seek(ld,!1)))a:{a=0;for(var b=u.enums;a<b.length;){var c=b[a];++a;for(var d=0,f=0,c=c.ctrList;f<c.length;){var e=c[f];++f;if(null!=e.node)if(d=C,C=qa,E=null,qa(e.node,[]),C=d,d=e.node,mb=!1,R(d,null),d=ga(e.node),"number"==typeof d)e.value=Math.floor(d),d=e.value+1;else{a=d!=
Rc?u.error("Enum values should be integer",e.node[2]):u.error("Enum values should be constant",e.node[2]);break a}else e.value=d++}}a=!1}if(a||this.seek(md,!1)||this.seek(qd,!0))return!0;mb=!0;u.seek(R);if(this.seek(kd,!0)||this.seek(rd,!1)||this.seek(hd,!0)||this.seek(sd,!0)||this.seek(pd,!0)||null==ya&&this.seek(id,!1))return!0;u=null;return!1}};var p={__ename__:!0};S.prototype={toString:function(){return this.src.name+("[L"+this.row+",c"+this.col+"]")}};var x={__ename__:!0};nb(ca,Error,{});nb(ja,
function(){this.b=""},{addLine:function(){this.b+=String.fromCodePoint(10);for(var a=this.indent;0<=--a;)this.b+=String.fromCodePoint(9)}});null==String.fromCodePoint&&(String.fromCodePoint=function(a){return 65536>a?String.fromCharCode(a):String.fromCharCode((a>>10)+55232)+String.fromCharCode((a&1023)+56320)});Object.defineProperty(ca.prototype,"message",{get:function(){return String(this.val)}});var qb,rb,aa,ba,ua,A="gml$self",G="gml$other",da=0,u,C,E,L,Eb,M,lb=Object.create(null),Qc=Object.create(null),
H=Object.create(null),za=!1,Sc=Object.create(null),ia=Object.create(null),xa=Object.create(null),ya=null;Object.create(null);Object.create(null);var Aa=Object.create(null),mb,Rc=[],O,V;(function(){var a=window.location;L=document.getElementById("game");switch(a.hostname){case "yal.cc":break;case "":case "localhost":break;default:window.alert("Redirecting to source website...");a.href="http://yal.cc/r/gml";return}window.searchParams||Object.create(null);Eb=document.getElementById("mode");window.lwModeChanged=
function(a){za=!1;Y(!0,!0)};document.getElementById("source");window.addEventListener("keydown",function(a){if(116==a.keyCode||13==a.keyCode&&a.ctrlKey)Y(!1),a.preventDefault(),a.stopPropagation()});document.getElementById("refresh").onclick=function(a){Y(!1)};document.getElementById("reload").onclick=function(a){Y(!0)};document.getElementById("stop").onclick=function(a){L.contentWindow.gml$game_end()};window.lwRunBlank=function(){Y(!0,!0)};window.lwRunGame=function(){Y(!1)};window.lwSetAPI=function(a){console.log("Bindings set");
lb=a.lwArg0;Qc=a.lwArg1;H=a.lwFlags;Sc=a.lwConst;xa=a.lwInst}})()})();

